/* ATOMOS Sci · pilot v0.1.0 — 사용자 화면. 비밀키를 포함하지 않습니다. */
(() => {
'use strict';
const C = window.ATOMOS_CONFIG || {};
const $ = (s, el = document) => el.querySelector(s);
const $$ = (s, el = document) => [...el.querySelectorAll(s)];
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id = () => crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2);
const fmt = (d, kind = 'date') => d ? new Intl.DateTimeFormat('ko-KR', { timeZone: 'Asia/Seoul', ...(kind === 'time' ? { month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false } : { year:'numeric',month:'numeric',day:'numeric' }) }).format(new Date(d)) : '기한 없음';
const dateInput = d => d ? new Intl.DateTimeFormat('en-CA', { timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit' }).format(new Date(d)) : '';
const localInput = d => { if (!d) return ''; const n = new Date(new Date(d).getTime() + 9*3600000); return n.toISOString().slice(0,16); };
const kst = d => d ? new Date(d + ':00+09:00').toISOString() : null;
const day = () => dateInput(new Date());
const asNum = n => Number(n) || 0;
const iconPaths = {
 home:'<rect x="3" y="3" width="7" height="7" rx="1.4"/><rect x="14" y="3" width="7" height="7" rx="1.4"/><rect x="3" y="14" width="7" height="7" rx="1.4"/><rect x="14" y="14" width="7" height="7" rx="1.4"/>',
 users:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M17 5a3 3 0 0 1 0 6m1 4a5 5 0 0 1 3 4v2"/>',
 classes:'<path d="M3 5c3-1 6-1 9 1 3-2 6-2 9-1v15c-3-1-6-1-9 1-3-2-6-2-9-1zM12 6v15"/>',
 assignments:'<rect x="5" y="4" width="14" height="18" rx="2"/><path d="M9 4V2h6v2M9 10h6M9 14h6M9 18h3"/>',
 records:'<path d="M4 3v18h18M8 16l4-5 4 2 5-8"/>',
 bank:'<path d="m12 3 9 5-9 5-9-5zm-9 9 9 5 9-5m-18 5 9 5 9-5"/>',
 settings:'<path d="m9 3-1 3-3 1 1 3-1 3 3 1 1 3 3-1 3 1 1-3 3-1-1-3 1-3-3-1-1-3-3 1z"/><circle cx="12" cy="10" r="3"/>',
 account:'<circle cx="12" cy="8" r="4"/><path d="M4 22v-2a8 8 0 0 1 16 0v2"/>',
 logout:'<path d="M9 3H4v18h5m7-14 5 5-5 5M9 12h12"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 3"/>',
 arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
 download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 play:'<path d="m8 4 12 8-12 8z"/>',
 plus:'<path d="M12 4v16M4 12h16"/>'
};
const icon = name => `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.55" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[name] || iconPaths.home}</svg>`;
const brand = () => '<div class="brand"><div class="brand-main">ATOMOS <em>Sci</em></div><div class="brand-sub">박지훈 · SCIENCE STUDIO</div></div>';
const demo = C.demo ? window.ATOMOS_DEMO() : null;
let sb = null, D = {}, currentUser = null, child = null, tab = 'home', chosenClass = null;
let previousSeen = null, editingLesson = null, photoFiles = [], cleanupVideo = null, bankLoaded = false;
let changing = false, renderedSeq = 0;
const state = () => ({ me: currentUser, data: D, studentId: studentId(), demo: !!demo });
const roleLabel = role => ({admin:'관리자',student:'학생',parent:'학부모'}[role] || '');
const label = {home:'대시보드',users:'학생·학부모',classes:'수업 공간',assignments:'과제 관리',bank:'문제은행',records:'학습 기록',settings:'관리자 설정',account:'내 계정'};
const studentId = () => currentUser?.role === 'student' ? currentUser.id : child;
const by = (t, key, value) => (D[t] || []).filter(x => x[key] === value);
const one = (t, value) => (D[t] || []).find(x => x.id === value);
const studentName = value => one('profiles', value)?.display_name || '학생';
const className = value => one('classes', value)?.name || '반';
const studentsOf = cid => by('enrollments','class_id',cid).filter(e=>e.access).map(e=>one('profiles',e.student_id)).filter(Boolean);
const classesOf = sid => by('enrollments','student_id',sid).map(e=>one('classes',e.class_id)).filter(Boolean);
const canAttendLesson = (sid,l) => (D.enrollments||[]).some(e=>e.student_id===sid&&e.class_id===l.class_id&&e.access&&dateInput(l.starts_at)>=e.joined_on&&(!e.left_on||dateInput(l.starts_at)<=e.left_on));
const relevantLessons = sid => (D.lessons||[]).filter(l=>!sid||canAttendLesson(sid,l));
const relevantAssignments = sid => (D.assignments||[]).filter(a=>{const l=one('lessons',a.lesson_id);return l&&(!sid||canAttendLesson(sid,l));});
const submissionFor = (assignment,sid=studentId()) => (D.submissions||[]).find(s=>s.assignment_id===assignment&&s.student_id===sid);
const statusPill = (s,a) => s ? `<span class="pill ${s.late?'warn':'good'}">${s.late?'기한 후 제출':'제출 완료'}</span>` : a.kind==='text'?'<span class="pill">안내형</span>':a.due_at&&Date.parse(a.due_at)<Date.now()?'<span class="pill bad">미제출</span>':'<span class="pill warn">제출 예정</span>';
const kindName = k => ({text:'텍스트 안내',photo:'사진 제출',quiz:'클릭 답안'}[k]||k);
const empty = (title,desc='') => `<div class="empty"><strong>${esc(title)}</strong>${esc(desc)}</div>`;
const field = (title,name,value='',type='text',extra='',help='') => `<div class="field"><label for="f-${name}">${esc(title)}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}>${help?`<small>${esc(help)}</small>`:''}</div>`;
const textArea = (title,name,value='',extra='') => `<div class="field"><label for="f-${name}">${esc(title)}</label><textarea id="f-${name}" name="${name}" ${extra}>${esc(value)}</textarea></div>`;
const select = (title,name,options,value='',extra='') => `<div class="field"><label for="f-${name}">${esc(title)}</label><select id="f-${name}" name="${name}" ${extra}>${options.map(o=>{const [v,t]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`;}).join('')}</select></div>`;
const formEnd = (text='저장하기') => `<p class="form-error" role="alert"></p><div class="dialog-actions"><button type="button" class="btn secondary" data-act="close-modal">닫기</button><button class="btn accent" type="submit">${esc(text)}</button></div></form>`;
const timeLabel = d => new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(d));
const dateTile = d => `<div class="date-tile"><small>${new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Seoul',month:'short'}).format(new Date(d)).toUpperCase()}</small><b>${new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Seoul',day:'numeric'}).format(new Date(d))}</b></div>`;
function toast(message) { const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),4500); }
function modal(title,html,wide=false) { stopVideo();$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;const el=$('#modal');el.classList.toggle('wide',wide);if(!el.open)el.showModal(); }
function closeModal() { stopVideo();$('#modal').close();$('#modal-body').replaceChildren();photoFiles=[]; }
function stopVideo(){if(cleanupVideo){cleanupVideo();cleanupVideo=null;}}
function userError(form,e){const el=$('.form-error',form);if(el)el.textContent=e.message||String(e);else toast(e.message||String(e));}
const delay = ms => new Promise(r=>setTimeout(r,ms));
async function sessionToken(){const {data,error}=await sb.auth.getSession();if(error||!data.session)throw new Error('로그인이 만료되었습니다. 다시 로그인해 주세요.');return data.session.access_token;}
async function api(action,data={},keepalive=false){
 if(demo)return demoAction(action,data);
 const token=action==='login'?null:await sessionToken();
 const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),45000);
 try{const res=await fetch(C.supabaseUrl.replace(/\/$/,'')+'/functions/v1/atomos-api',{method:'POST',headers:{'Content-Type':'application/json','apikey':C.publicKey,...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({action,...data}),signal:controller.signal,keepalive});let r;try{r=await res.json();}catch{throw new Error('서버 응답을 읽지 못했습니다. Edge Function 배포와 JWT 설정을 확인하세요.');}if(!res.ok||r.ok===false)throw new Error(r.error||'요청이 실패했습니다.');return r;}
 catch(e){if(e.name==='AbortError')throw new Error('응답이 지연되었습니다. 다시 시도하기 전에 저장 여부를 확인해 주세요.');if(e instanceof TypeError)throw new Error('인터넷 연결 또는 서버 주소·APP_URL을 확인해 주세요.');throw e;}finally{clearTimeout(timer);}
}
async function readAll(table){let out=[];for(let from=0;;from+=500){const {data,error}=await sb.from('app_'+table).select('*').range(from,from+499);if(error)throw new Error(`${table} 조회 실패: DB 설치와 접근 권한을 확인하세요.`);out=out.concat(data);if(data.length<500)return out;if(from>=49500)throw new Error('이 화면의 조회 한도를 넘었습니다. 기간별 조회 확장이 필요합니다. 데이터는 삭제되지 않았습니다.');}}
async function loadData(){
 if(demo){D=demo;currentUser=D.profiles.find(p=>p.id===currentUser?.id)||currentUser;return;}
 const {data:auth}=await sb.auth.getUser();if(!auth.user)throw new Error('다시 로그인해 주세요.');
 const {data:p,error}=await sb.from('app_profiles').select('*').eq('id',auth.user.id).single();if(error)throw new Error('계정 정보가 없습니다. 설치 도우미에서 관리자 생성을 확인하세요.');currentUser=p;
 if(p.must_change){D={profiles:[p]};return;}
 const tables=['profiles','family_links','classes','enrollments','lessons','assignments','assignment_items','submissions','responses','attendance','scores','watch','worksheets'];
 const results=await Promise.all(tables.map(readAll));D=Object.fromEntries(tables.map((t,i)=>[t,results[i]]));
 if(bankLoaded&&p.role==='admin')D.questions=await readAll('questions');
}
async function refresh(){await loadData();await render();}
function navigate(next){stopVideo();chosenClass=null;tab=next;render().catch(e=>toast(e.message));}
function pageTitle(eyebrow,title,description='',actions=''){return `<div class="page-title"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1>${description?`<p>${esc(description)}</p>`:''}</div>${actions}</div>`;}
function metric(name,value,unit,foot,ic='records',positive=false){return `<div class="metric"><div class="row between"><div class="metric-icon">${icon(ic)}</div><small class="muted">ATOMOS / RECORD</small></div><div class="label">${esc(name)}</div><div class="value">${esc(value)}<span>${esc(unit)}</span></div><div class="foot ${positive?'positive':''}">${esc(foot)}</div></div>`;}
function shell(){
 const role=currentUser.role;const navs=role==='admin'?['home','users','classes','assignments','bank','settings']:role==='parent'?['home','classes','records','account']:['home','classes','assignments','records','account'];
 const nav=n=>`<button class="nav-link ${tab===n?'active':''}" data-act="nav" data-id="${n}">${icon(n)}<span>${esc(label[n])}</span></button>`;
 const selected=child?studentName(child):'';
 $('#root').innerHTML=`<aside class="sidebar">${brand()}<div class="nav-label">${role==='admin'?'STUDIO MANAGEMENT':'MY LEARNING SPACE'}</div><nav>${navs.map(nav).join('')}</nav><div class="side-bottom"><div class="side-support"><strong>Small steps. Real growth.</strong>배움의 과정을 기록하고,<br>성장의 다음 단계를 함께합니다.</div>${role==='admin'?nav('account'):''}<button class="nav-link" data-act="logout">${icon('logout')}로그아웃</button></div></aside><div class="workspace">${demo?'<div class="demo-banner">가상 데이터 미리보기 · 실제 계정이나 개인정보를 입력하지 마세요. 새로고침하면 체험 기록이 초기화됩니다.</div>':''}<header class="topbar"><div class="breadcrumbs"><span>ATOMOS SCI</span><span>/</span><strong>${esc(label[tab]||'학습 공간')}</strong></div><div class="mobile-brand">${brand()}</div><div class="row gap8">${role==='parent'&&selected?`<button class="child-switch" data-act="choose-child">${esc(selected)} ↕</button>`:''}<div class="top-user row gap8"><div class="avatar">${esc(currentUser.display_name.slice(0,1))}</div><div>${esc(role==='parent'?'학부모님':currentUser.display_name)}<small>${esc(roleLabel(role))} · ${demo?'화면 체험':'학습 공간'}</small></div></div></div></header><main class="main" id="main"></main></div><nav class="mobile-nav">${navs.filter(n=>role!=='admin'||n!=='assignments').map(n=>`<button class="${tab===n?'active':''}" data-act="nav" data-id="${n}">${icon(n)}<span>${esc(label[n])}</span></button>`).join('')}</nav>`;
}
function loginView(message=''){
 $('#root').innerHTML=`<div class="login"><section class="login-art">${brand()}<div class="statement"><div><h1>과학을 이해하는 힘,<br>스스로 나아가는 자신감.</h1><div class="en">A clearer tomorrow.</div></div><p class="art-caption">매 수업의 작은 변화가 쌓여<br>학생의 다음 가능성이 됩니다.<br>그 모든 과정을, 이곳에서 함께합니다.</p></div><div class="orbit"></div><div class="year">ATOMOS SCIENCE STUDIO &nbsp; / &nbsp; LEARNING JOURNAL</div></section><section class="login-panel"><div class="login-inner"><div class="eyebrow">YOUR LEARNING, CONNECTED</div><h2>반갑습니다.</h2><p>나의 배움, 우리 아이의 성장과 만나는 곳.</p>${demo?'<div class="notice warn mb">가상 데이터 화면 체험입니다. 실제 개인정보를 입력하지 마세요.</div>':''}<form data-form="login">${field('아이디','username','','text','required autocomplete="username" autocapitalize="none" spellcheck="false" placeholder="아이디를 입력해 주세요"')}${field('비밀번호','password','','password','required autocomplete="current-password" placeholder="비밀번호를 입력해 주세요"')}<p class="form-error" role="alert">${esc(message)}</p><button class="btn full" type="submit">로그인 ${icon('arrow')}</button></form><p class="login-footer">아이디를 잊으셨나요? 선생님께 문의해 주세요.<br>계정 유형은 로그인 후 자동으로 확인됩니다.</p>${demo?'<details class="demo-note"><summary>화면 체험용 아이디 확인하기</summary><p>관리자: <b>박지훈</b> / <b>1234</b><br>학생: <b>학생01</b> / <b>1234</b><br>학부모: <b>학부모01</b> / <b>1234</b><br>학부모 계정에는 가상 자녀 2명이 연결되어 있습니다.</p></details>':'<p class="login-footer"><a href="./privacy.html" target="_blank" rel="noopener">개인정보 처리 안내</a> · 공유 기기에서는 사용 후 로그아웃해 주세요.</p>'}</div></section></div>`;
}
async function render(){
 const seq=++renderedSeq;
 if(!currentUser)return loginView();
 if(currentUser.must_change){tab='account';shell();$('#main').innerHTML=pageTitle('FIRST SIGN-IN','초기 비밀번호를 변경해 주세요.','학생 정보를 열기 전에 계정 보안을 먼저 설정합니다.')+accountView(true);return;}
 shell();const el=$('#main');
 if(currentUser.role==='parent'&&!child&&tab!=='account'){el.innerHTML=childrenView();return;}
 if(tab==='home')el.innerHTML=currentUser.role==='admin'?adminHome():learnerHome();
 else if(tab==='users')el.innerHTML=usersView();
 else if(tab==='classes')el.innerHTML=chosenClass?classDetail(chosenClass):classesView();
 else if(tab==='assignments')el.innerHTML=assignmentsView();
 else if(tab==='records')el.innerHTML=recordsView();
 else if(tab==='account')el.innerHTML=pageTitle('YOUR ACCOUNT','내 계정','아이디가 바뀌어도 학습 기록과 가족 연결은 그대로 유지됩니다.')+accountView();
 else if(tab==='settings'){el.innerHTML=settingsView();loadDriveStatus().catch(e=>{const t=$('#drive-state');if(t)t.textContent=e.message;});}
 else if(tab==='bank'){
 el.innerHTML=pageTitle('QUESTION STUDIO','문제은행','원본을 보존하고, 검수된 문항으로 다음 학습을 만듭니다.')+'<div id="bank-root"><div class="loading-layout"><div class="skeleton"></div><div class="skeleton"></div></div></div>';
 if(!demo){D.questions=await readAll('questions');bankLoaded=true;}else D.questions=D.questions||[];
 if(seq!==renderedSeq)return;
 await window.AtomosBank.mount($('#bank-root'),{esc,icon,field,textArea,select,modal,closeModal,toast,api,upload,assetURL,readAll,refresh,state:state(),config:C,questions:D.questions||[],saveFile,compressImage});
 }
 else el.innerHTML=empty('화면을 찾을 수 없습니다.');
}
function childrenView(){
 const children=by('family_links','parent_id',currentUser.id).map(l=>one('profiles',l.student_id)).filter(Boolean);
 return `<div class="welcome"><div class="welcome-head"><div class="eyebrow">WELCOME TO THE LEARNING JOURNEY</div><h1>함께 쌓아온 시간,<br>오늘의 성장으로.</h1><p>수업의 내용부터 과제와 성적의 변화까지.<br>우리 아이가 어떻게 배우고 있는지 차근차근 살펴보세요.</p></div>${children.length?`<div class="${children.length===1?'':'grid2'}">${children.map(p=>`<button class="child-card" data-act="select-child" data-id="${esc(p.id)}"><div class="avatar">${esc(p.display_name.slice(0,1))}</div><span class="pill good">${esc(p.school||'ATOMOS Sci')} ${esc(p.grade)}</span><h3 class="mt">${esc(p.display_name)}</h3><p>${classesOf(p.id).length}개 반의 학습 기록이 이어지고 있습니다.</p><div class="arrow">성장 기록 살펴보기 &nbsp; →</div></button>`).join('')}</div>`:empty('아직 연결된 학생이 없습니다.','선생님이 학부모 계정에 학생을 연결하면 학습 기록을 볼 수 있습니다.')}<p class="tour-caption">${children.length>1?'자녀마다 기록은 따로, 계정은 하나로 관리됩니다.':'반이 바뀌어도 학생의 학습 기록은 계속 이어집니다.'}</p></div>`;
}
function adminHome(){
 const students=(D.profiles||[]).filter(p=>p.role==='student'&&p.active);const activeClasses=(D.classes||[]).filter(c=>c.active&&c.starts_on<=day()&&c.ends_on>=day());
 const pending=(D.submissions||[]).filter(s=>one('assignments',s.assignment_id)?.kind==='photo'&&!s.feedback);
 const lessons=[...(D.lessons||[])].sort((a,b)=>Date.parse(a.starts_at)-Date.parse(b.starts_at));const upcoming=lessons.filter(l=>dateInput(l.starts_at)>=day()).slice(0,3);
 const recent=[...(D.submissions||[])].sort((a,b)=>Date.parse(b.submitted_at)-Date.parse(a.submitted_at)).slice(0,5);
 return pageTitle('TEACHER WORKSPACE','좋은 수업의 시작, 오늘의 기록.','학생의 작은 변화까지 놓치지 않는 ATOMOS Sci 학습 공간입니다.',`<span class="pill">${esc(fmt(new Date()))}</span>`)+
 `<div class="hero"><div><span class="pill dark">SCIENCE, WITH CLARITY.</span><h2>쌓이는 하루,<br>선명해지는 실력.</h2><p>수업을 준비하고, 배움을 기록하고, 다음 성장을 설계합니다.</p></div><div class="hero-side"><div class="big">${String(upcoming.length).padStart(2,'0')}</div><small>UPCOMING CLASSES</small><br><button class="btn" data-act="nav" data-id="classes">수업 공간 열기 ${icon('arrow')}</button></div></div>`+
 `<div class="grid4 mt">${metric('함께 배우는 학생',students.length,'명','활성 학생 계정','users')}${metric('운영 중인 반',activeClasses.length,'개','오늘 날짜 기준','classes')}${metric('확인할 사진 과제',pending.length,'건','피드백 작성 전 제출물','assignments')}${metric('누적 수업 기록',(D.lessons||[]).length,'회','모든 반의 등록 수업','clock')}</div>`+
 `<div class="dashboard-columns"><section class="card"><div class="section-heading"><h2>다가오는 수업</h2><button class="text-btn" data-act="nav" data-id="classes">전체 수업 →</button></div>${upcoming.length?upcoming.map(lessonItem).join(''):empty('예정된 수업이 없습니다.','반을 만들고 첫 수업을 추가해 보세요.')}</section><section class="card"><div class="section-heading"><h2>과제 제출 소식</h2><button class="text-btn" data-act="nav" data-id="assignments">전체 보기 →</button></div>${recent.length?recent.map(s=>`<div class="list-row"><div><h4>${esc(studentName(s.student_id))} <span class="muted">· ${esc(one('assignments',s.assignment_id)?.title||'과제')}</span></h4><p>${esc(fmt(s.submitted_at,'time'))}</p></div><button class="pill ${s.late?'warn':'good'}" data-act="view-submission" data-id="${esc(s.id)}">${s.feedback?'피드백 완료':'확인하기'}</button></div>`).join(''):empty('아직 제출된 과제가 없습니다.')}</section></div>`+
 `<section class="card mt"><div class="section-heading"><div><h2>학생에게 더 가까운 관리</h2><p class="small muted">기록을 쌓고, 실제 수업의 가치를 전달하세요.</p></div></div><div class="grid3"><button class="material-link" data-act="new-user"><span>학생·학부모 계정 만들기</span>${icon('plus')}</button><button class="material-link" data-act="family-modal"><span>학부모에게 자녀 연결하기</span>${icon('users')}</button><button class="material-link" data-act="new-score"><span>평가 성적 기록하기</span>${icon('records')}</button></div></section>`;
}
function lessonItem(l){return `<div class="lesson-item">${dateTile(l.starts_at)}<div class="grow"><span class="pill">${esc(one('classes',l.class_id)?.subject||'과학')}</span><h3>${esc(l.title)}</h3><p>${esc(className(l.class_id))} · ${timeLabel(l.starts_at)} · ${l.duration_min}분</p></div><button class="btn secondary tiny" data-act="lesson" data-id="${esc(l.id)}">수업 보기</button></div>`;}
function studentStats(sid){
 const attended=by('attendance','student_id',sid).filter(a=>['present','late'].includes(a.status));const minutes=attended.reduce((n,a)=>n+(one('lessons',a.lesson_id)?.duration_min||0),0);
 const due=relevantAssignments(sid).filter(a=>a.kind!=='text'&&a.due_at&&Date.parse(a.due_at)<Date.now());const done=due.filter(a=>submissionFor(a.id,sid)).length;
 const scores=by('scores','student_id',sid).sort((a,b)=>a.assessed_on.localeCompare(b.assessed_on));const latest=scores.at(-1);const previous=latest?[...scores].reverse().find(x=>x.id!==latest.id&&x.class_id===latest.class_id):null;
 const delta=latest&&previous?Math.round((latest.score/latest.max_score-previous.score/previous.max_score)*1000)/10:null;
 return {attended,minutes,due,done,scores,latest,delta};
}
function learnerHome(){
 const sid=studentId();const p=one('profiles',sid);if(!p)return empty('학습 기록을 불러오지 못했습니다.');const parent=currentUser.role==='parent';const st=studentStats(sid);
 const missions=relevantAssignments(sid).filter(a=>a.kind!=='text'&&!submissionFor(a.id,sid)).sort((a,b)=>(Date.parse(a.due_at)||Infinity)-(Date.parse(b.due_at)||Infinity)).slice(0,3);
 const lessons=relevantLessons(sid).sort((a,b)=>Date.parse(b.starts_at)-Date.parse(a.starts_at));
 const feedback=by('submissions','student_id',sid).filter(s=>s.feedback).sort((a,b)=>Date.parse(b.submitted_at)-Date.parse(a.submitted_at))[0];
 const welcome=parent&&(!previousSeen||Date.now()-Date.parse(previousSeen)>7*86400000);
 return pageTitle(parent?'PARENT LEARNING JOURNAL':'YOUR LEARNING JOURNAL',parent?`${p.display_name} 학생의 배움이 이어지고 있습니다.`:`${p.display_name} 학생, 오늘도 한 걸음 더.`,parent?'결과뿐 아니라, 결과를 만들어 가는 과정까지 살펴보세요.':'오늘의 할 일을 확인하고, 나의 학습 기록을 이어 가세요.')+
 `<div class="hero"><div><span class="pill dark">${welcome?'WELCOME BACK, TO YOUR CHILD’S GROWTH.':'SMALL STEPS. REAL GROWTH.'}</span><h2>${parent?'함께 쌓아온 시간,<br>더 단단해진 오늘.':'배운 것을 내 것으로.<br>한 문제씩, 확실하게.'}</h2><p>${parent?`${esc(p.display_name)} 학생은 현재까지 ${st.attended.length}회의 출석 기록을 쌓았습니다. 수업·과제·피드백이 이곳에 함께 남습니다.`:'점수만큼 중요한 것은 풀이의 근거를 설명하는 힘입니다. 오늘 배운 개념을 문제에 연결해 보세요.'}</p></div><div class="hero-side"><div class="big">${st.attended.length}</div><small>CLASSES TOGETHER</small></div></div>`+
 `<div class="grid4 mt">${metric('누적 출석',st.attended.length,'회',`기록된 수업 ${Math.round(st.minutes/60)}시간 · 지각 포함`,'classes')}${metric('최근 평가',st.latest?Math.round(st.latest.score/st.latest.max_score*100):'—','점',st.latest?st.latest.title:'아직 성적 기록이 없습니다.','records')}${metric('같은 반 직전 평가 대비',st.delta===null?'—':(st.delta>0?'+':'')+st.delta,'p','같은 반 · 난이도 보정 없는 100점 환산','records',st.delta>0)}${metric('마감 과제 제출률',st.due.length?Math.round(st.done/st.due.length*100):'—','%',`${st.done}/${st.due.length}건 · 온라인 과제만 집계`,'assignments')}</div>`+
 `<div class="dashboard-columns"><section class="card"><div class="section-heading"><h2>${parent?'최근 평가의 흐름':'나의 성적 흐름'}</h2><button class="text-btn" data-act="nav" data-id="records">상세 기록 →</button></div>${chart(st.scores.filter(x=>!st.latest||x.class_id===st.latest.class_id).slice(-6))}<p class="small-info">시험마다 범위와 난이도가 다를 수 있습니다. 점수 변화만으로 실력 향상을 단정하지 않습니다.</p></section><section class="card"><div class="section-heading"><h2>${parent?'함께 챙겨 주세요':'오늘의 학습 미션'}</h2><button class="text-btn" data-act="nav" data-id="${parent?'classes':'assignments'}">전체 보기 →</button></div>${missions.length?missions.map(a=>`<div class="list-row"><div><h4>${esc(a.title)}</h4><p>${esc(kindName(a.kind))} · ${esc(fmt(a.due_at,'time'))}</p></div><button class="btn soft tiny" data-act="assignment" data-id="${esc(a.id)}">${parent?'확인':'열기'}</button></div>`).join(''):empty('미제출 과제가 없습니다.','계속해서 좋은 학습 습관을 이어 가세요.')}</section></div>`+
 `<div class="dashboard-columns"><section class="card"><div class="section-heading"><h2>이렇게 배우고 있어요</h2><button class="text-btn" data-act="nav" data-id="classes">수업 전체 →</button></div>${lessons.slice(0,3).map(lessonItem).join('')||empty('아직 등록된 수업이 없습니다.')}</section><section class="card"><div class="section-heading"><h2>선생님의 피드백</h2><span class="eyebrow">TEACHER’S NOTE</span></div>${feedback?`<div class="feedback-box pre">${esc(feedback.feedback)}</div><p class="small-info mt">${esc(one('assignments',feedback.assignment_id)?.title||'과제')} · ${esc(fmt(feedback.submitted_at))}</p>`:empty('다음 피드백을 기다리고 있습니다.','작성된 피드백만 표시합니다.')}<div class="notice mt">${parent?'수업이 달라져도 기록은 계속 이어집니다. 자녀 선택 버튼으로 형제·자매의 기록을 바꿔 볼 수 있습니다.':'사이트 안에서 영상을 보면 재생 중이고 페이지가 보이는 시간에 근거해 시청 시간이 기록됩니다.'}</div></section></div>`;
}
function chart(scores){
 if(!scores.length)return empty('아직 성적 기록이 없습니다.','평가 결과가 등록되면 변화가 표시됩니다.');
 const w=500,h=180,pad=28,ys=n=>h-28-n/100*(h-48),xs=i=>scores.length===1?w/2:pad+i*(w-2*pad)/(scores.length-1);
 const pts=scores.map((s,i)=>[xs(i),ys(s.score/s.max_score*100)]);const path=pts.map((p,i)=>(i?'L':'M')+p[0]+','+p[1]).join(' ');
 return `<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="최근 평가 성적 추이, 100점 환산"><title>${esc(scores.map(s=>s.title+' '+Math.round(s.score/s.max_score*100)+'점').join(', '))}</title>${[0,50,100].map(n=>`<line class="grid" x1="${pad}" x2="${w-pad}" y1="${ys(n)}" y2="${ys(n)}"/><text x="2" y="${ys(n)+3}">${n}</text>`).join('')}<path class="curve" d="${path}"/>${scores.map((s,i)=>`<circle class="point" cx="${pts[i][0]}" cy="${pts[i][1]}" r="4"/><text class="value-label" x="${pts[i][0]}" y="${pts[i][1]-11}" text-anchor="middle">${Math.round(s.score/s.max_score*100)}</text><text x="${pts[i][0]}" y="${h-6}" text-anchor="middle">${esc(s.assessed_on.slice(5).replace('-','.'))}</text>`).join('')}</svg>`;
}
function usersView(){return pageTitle('PEOPLE & CONNECTIONS','학생·학부모','같은 학생은 한 계정으로, 가족은 하나의 연결로 관리합니다.',`<button class="btn accent" data-act="new-user">${icon('plus')} 계정 추가</button>`)+`<div class="toolbar"><input class="input" id="user-search" placeholder="이름 · 아이디 · 학교 검색" aria-label="계정 검색"><select class="input" id="user-role" aria-label="계정 종류"><option value="">전체 계정</option value="student">학생</option><option value="parent">학부모</option><option value="admin">관리자</option></select><button class="btn secondary" data-act="family-modal">자녀 연결</button></div><div class="card"><div class="table-wrap"><table><thead><tr><th>이름 / 아이디</th><th>구분</th><th>학교 / 반</th><th>연결된 가족</th><th>관리</th></tr></thead><tbody id="users-body">${userRows()}</tbody></table></div></div><div class="notice mt">관리자도 기존 비밀번호를 열람하지 않습니다. 비밀번호를 잊은 계정에는 새 초기 비밀번호를 발급할 수 있습니다.</div>`;}
function userRows(){const q=($('#user-search')?.value||'').toLowerCase(),r=$('#user-role')?.value||'';return (D.profiles||[]).filter(p=>(!r||p.role===r)&&[p.display_name,p.username,p.school].join(' ').toLowerCase().includes(q)).map(p=>`<tr><td><div class="student-cell"><div class="avatar">${esc(p.display_name.slice(0,1))}</div><div><b>${esc(p.display_name)}</b><small>${esc(p.username)}${!p.active?' · 비활성':''}</small></div></div></td><td><span class="pill">${esc(roleLabel(p.role))}</span></td><td>${esc(p.school||'—')}<small>${esc(p.role==='student'?classesOf(p.id).map(c=>c.name).join(', '):'')}</small></td><td>${esc(p.role==='parent'?by('family_links','parent_id',p.id).map(l=>studentName(l.student_id)).join(', ')||'연결 전':p.role==='student'?by('family_links','student_id',p.id).map(l=>one('profiles',l.parent_id)?.username).join(', ')||'연결 전':'—')}</td><td><div class="question-table-actions">${p.role==='student'?`<button class="btn secondary tiny" data-act="assign-existing" data-id="${esc(p.id)}">반 배정</button>`:''}${p.id!==currentUser.id?`<button class="btn secondary tiny" data-act="reset-password" data-id="${esc(p.id)}">암호 초기화</button><button class="text-btn" data-act="toggle-active" data-id="${esc(p.id)}">${p.active?'비활성화':'활성화'}</button>`:'<button class="text-btn" data-act="nav" data-id="account">내 계정</button>'}</div></td></tr>`).join('')||'<tr><td colspan="5">검색 결과가 없습니다.</td></tr>';}
function newUserModal(){modal('학생·학부모 계정 추가',`<form data-form="create-user">${select('계정 종류','role',[['student','학생'],['parent','학부모']],'student')}${field('이름','display_name','','text','required maxlength="60" placeholder="예: 김민준"')}<div id="duplicate-users"></div><div class="form-grid">${field('학교 (학생만)','school','','text','maxlength="100"')}${field('학년 (학생만)','grade','','text','maxlength="30"')}</div>${field('로그인 아이디','username','','text','required minlength="2" maxlength="40" autocomplete="off" placeholder="예: student2026"')}${field('초기 비밀번호','password','','text',`required minlength="${demo?4:12}" maxlength="128" autocomplete="off"`,'운영에서는 영문·숫자를 포함한 12자 이상. 첫 로그인 시 변경합니다.')}<button class="text-btn" type="button" data-act="random-password">안전한 초기 비밀번호 자동 만들기</button><div class="notice mt">기존 학생이 의심되면 아래 후보에서 ‘기존 학생 배정’을 사용하세요. 동명이인은 학교·학년을 확인한 뒤 별도로 등록합니다.</div><label class="check"><input type="checkbox" name="confirmed_distinct">동명이인 후보가 있다면 서로 다른 학생임을 확인했습니다.</label>${formEnd('계정 만들기')}`);}
function duplicateUsers(){const el=$('#duplicate-users');if(!el)return;const name=$('[name="display_name"]',$('#modal'))?.value.trim();const role=$('[name="role"]',$('#modal'))?.value;const matches=(D.profiles||[]).filter(p=>p.role==='student'&&p.display_name===name);el.innerHTML=role==='student'&&matches.length?`<div class="notice warn mb"><b>이미 등록된 학생일 수 있습니다.</b>${matches.map(p=>`<div class="row between mt"><span>${esc(p.display_name)} · ${esc(p.school)} ${esc(p.grade)}<br>${esc(p.username)}</span><button type="button" class="btn secondary tiny" data-act="assign-existing" data-id="${esc(p.id)}">기존 학생 배정</button></div>`).join('')}</div>`:'';}
function enrollModal(sid='',cid=''){modal('기존 학생을 반에 배정',`<form data-form="enroll">${select('학생','student_id',(D.profiles||[]).filter(p=>p.role==='student').map(p=>[p.id,`${p.display_name} · ${p.username} · ${p.school}`]),sid,'required')}${select('반','class_id',(D.classes||[]).map(c=>[c.id,c.name]),cid,'required')}${field('학습 기록 연결 시작일','joined_on',cid?one('classes',cid)?.starts_on:day(),'date','required','이 날짜 이후 수업이 보입니다. 반 개강일부터 보려면 개강일로 설정하세요.')}<div class="notice">학생 고유번호는 유지합니다. 여러 반을 동시에 수강해도, 다음 해 새 반에 등록해도 기록이 이어집니다.</div>${formEnd('이 학생 배정하기')}`);}
function familyModal(){const parents=(D.profiles||[]).filter(p=>p.role==='parent');modal('학부모에게 자녀 연결',parents.length?`<form data-form="family-link">${select('학부모','parent_id',parents.map(p=>[p.id,`${p.display_name} · ${p.username}`]))}${select('연결할 학생','student_id',(D.profiles||[]).filter(p=>p.role==='student').map(p=>[p.id,`${p.display_name} · ${p.school} ${p.grade}`]))}<div class="notice">한 학부모에게 여러 학생을 연결할 수 있습니다. 학생의 비밀번호를 학부모에게 공유하지 않습니다.</div><div class="mt"><h3>현재 가족 연결</h3><div class="stack mt">${(D.family_links||[]).map(l=>`<div class="row between"><span class="small">${esc(one('profiles',l.parent_id)?.username)} → ${esc(studentName(l.student_id))}</span><button class="btn secondary tiny" type="button" data-act="unlink-family" data-parent="${esc(l.parent_id)}" data-id="${esc(l.student_id)}">연결 해제</button></div>`).join('')||'<p class="small muted">아직 연결이 없습니다.</p>'}</div></div>${formEnd('자녀 추가 연결')}`:empty('먼저 학부모 계정을 만들어 주세요.'));}
function classesView(){let list=currentUser.role==='admin'?(D.classes||[]):classesOf(studentId());return pageTitle('CLASSROOMS','매 수업을 연결하는 공간','수업 내용, 과제, 자료와 영상을 한곳에서 확인합니다.',currentUser.role==='admin'?`<button class="btn accent" data-act="new-class">${icon('plus')} 반 만들기</button>`:'')+`<div class="grid3">${list.map((c,i)=>`<article class="class-card"><div class="row between"><div class="class-num">CLASS ${String(i+1).padStart(2,'0')}</div><span class="pill ${c.active?'good':''}">${c.active?'학습 기록':'종료된 반'}</span></div><span class="eyebrow">${esc(c.subject)}</span><h3>${esc(c.name)}</h3><p>${esc(c.schedule)}</p><p>${esc(fmt(c.starts_on))} – ${esc(fmt(c.ends_on))}</p><div class="bottom"><span>${by('lessons','class_id',c.id).length}개 수업${currentUser.role==='admin'?` · ${studentsOf(c.id).length}명`:''}</span><button class="btn soft tiny" data-act="class" data-id="${esc(c.id)}">수업 공간 →</button></div></article>`).join('')||empty('연결된 반이 없습니다.','관리자가 학생을 반에 배정하면 수업이 표시됩니다.')}</div>`;}
function classDetail(cid){const c=one('classes',cid);if(!c)return empty('반을 찾을 수 없습니다.');const admin=currentUser.role==='admin';const ls=by('lessons','class_id',cid).sort((a,b)=>Date.parse(b.starts_at)-Date.parse(a.starts_at));return `<button class="text-btn mb" data-act="nav" data-id="classes">← 모든 반 보기</button>`+pageTitle(c.subject,c.name,c.schedule,admin?`<div class="row wrap"><button class="btn secondary" data-act="edit-class" data-id="${esc(cid)}">반 수정</button><button class="btn accent" data-act="new-lesson" data-id="${esc(cid)}">수업 추가</button></div>`:'')+`<div class="notice mb">개강 ${esc(fmt(c.starts_on))} · 종강 ${esc(fmt(c.ends_on))} · ${esc(c.schedule)}</div><div class="${admin?'dashboard-columns':''}"><section class="card"><div class="section-heading"><h2>수업 기록</h2><span class="pill">${ls.length}회 등록</span></div>${ls.map(lessonItem).join('')||empty('첫 수업을 추가해 주세요.')}</section>${admin?`<aside class="card"><div class="section-heading"><h2>수강 학생</h2><button class="text-btn" data-act="enroll-class" data-id="${esc(cid)}">학생 배정 +</button></div>${studentsOf(cid).map(p=>`<div class="list-row"><div><h4>${esc(p.display_name)}</h4><p>${esc(p.school)} ${esc(p.grade)} · ${esc(p.username)}</p></div><button class="btn secondary tiny" data-act="new-score" data-student="${esc(p.id)}" data-class="${esc(cid)}">성적 입력</button></div>`).join('')||empty('수강 학생이 없습니다.')}</aside>`:''}</div>`;}
function classModal(c={}){modal(c.id?'반 정보 수정':'새 반 만들기',`<form data-form="save-class" data-id="${esc(c.id||'')}">${field('반 이름','name',c.name||'','text','required maxlength="100" placeholder="예: 북일고 51기 통합과학2"')}${select('과목','subject',['통합과학','화학','물질과 에너지','화학 반응의 세계'],c.subject||'통합과학')}${field('수업 요일과 시간','schedule',c.schedule||'','text','required placeholder="예: 매주 토요일 18:00–21:00"')}<div class="form-grid">${field('개강일','starts_on',c.starts_on||day(),'date','required')}${field('종강일','ends_on',c.ends_on||day(),'date','required')}</div><label class="check"><input type="checkbox" name="active" ${c.active!==false?'checked':''}>운영 중인 반으로 표시</label>${formEnd()}`);}
function lessonModal(l={},cid=''){editingLesson=l;modal(l.id?'수업 기록 수정':'수업 기록 추가',`<form data-form="save-lesson" data-id="${esc(l.id||'')}">${select('반','class_id',(D.classes||[]).map(c=>[c.id,c.name]),l.class_id||cid,'required')}${field('수업 제목','title',l.title||'','text','required maxlength="200"')}<div class="form-grid">${field('수업 시작 (한국 시간)','starts_at',localInput(l.starts_at)||day()+'T18:00','datetime-local','required')}${field('수업 시간 (분)','duration_min',l.duration_min||180,'number','min="1" max="720" required')}</div>${textArea('오늘 수업 내용','content',l.content||'','required')}${textArea('학습 안내 / 선생님 메모 (학생·학부모에게 공개)','note',l.note||'')}${textArea('참고자료 링크 (한 줄에 자료 이름 | https://주소)','material_links',(l.materials||[]).filter(m=>m.url).map(m=>m.name+' | '+m.url).join('\n'))}<div class="field"><label>참고자료 파일 추가 (PDF·사진, 각 50MB 이하)</label><input type="file" name="material_files" accept="application/pdf,image/jpeg,image/png,image/webp" multiple></div>${(l.materials||[]).filter(m=>m.asset_id).map(m=>`<label class="check"><input type="checkbox" name="keep_material" value="${esc(m.asset_id)}" checked>${esc(m.name)} 유지</label>`).join('')}${select('수업 영상','video_kind',[['none','영상 없음'],['youtube','YouTube 링크'],['url','직접 재생 가능한 HTTPS 영상 주소'],['upload','MP4 / WebM 파일 업로드 (50MB 이하)']],l.video_kind||'none')}${field('영상 링크','video_url',l.video_url||'','url','placeholder="https://www.youtube.com/watch?v=..."')}<div class="field"><label>영상 파일 (업로드형일 때)</label><input type="file" name="video_file" accept="video/mp4,video/webm"><small>긴 수업 영상은 YouTube 링크를 권장합니다. 새 파일이 없으면 기존 업로드 영상을 유지합니다.</small></div><div class="notice">숙제는 수업을 저장한 뒤 수업 화면의 ‘과제 추가’에서 등록합니다.</div>${formEnd('수업 저장')}`,true);}
async function lessonView(lid){const l=one('lessons',lid);if(!l)return;const admin=currentUser.role==='admin';const tasks=by('assignments','lesson_id',lid);modal(l.title,`<div class="row wrap between"><span class="pill">${esc(className(l.class_id))}</span><span class="small muted">${esc(fmt(l.starts_at,'time'))} · ${l.duration_min}분</span></div>${admin?`<div class="row wrap mt"><button class="btn secondary tiny" data-act="edit-lesson" data-id="${esc(lid)}">수업 수정</button><button class="btn secondary tiny" data-act="attendance-modal" data-id="${esc(lid)}">출결 기록</button><button class="btn soft tiny" data-act="new-assignment" data-id="${esc(lid)}">과제 추가</button></div>`:''}<div class="detail-section"><h3>오늘 수업 내용</h3><div class="pre">${esc(l.content||'등록된 수업 내용이 없습니다.')}</div></div>${l.note?`<div class="detail-section"><h3>선생님의 학습 안내</h3><div class="feedback-box pre">${esc(l.note)}</div></div>`:''}<div class="detail-section"><h3>참고자료</h3><div class="stack">${(l.materials||[]).map(m=>m.asset_id?`<button class="material-link" data-act="asset" data-id="${esc(m.asset_id)}"><span>${esc(m.name)}</span>${icon('download')}</button>`:`<a class="material-link" href="${esc(safeURL(m.url))}" target="_blank" rel="noopener noreferrer"><span>${esc(m.name)}</span>${icon('download')}</a>`).join('')||'<p class="small muted">등록된 참고자료가 없습니다.</p>'}</div></div>${l.video_kind&&l.video_kind!=='none'?`<div class="detail-section"><h3>수업 영상</h3><div class="notice mb">학생 계정은 재생 상태·페이지 표시 상태·누적 시간을 기록합니다. 카메라나 다른 앱의 내용은 수집하지 않으며, 실제 집중을 증명하는 수치는 아닙니다.</div><div class="video-box" id="video-box"><div id="video-player"></div></div><div class="watch-meter"><span class="dot"></span><span id="watch-status">영상을 준비하고 있습니다.</span><b id="watch-seconds"></b></div>${l.video_kind==='youtube'?`<a class="text-btn" href="${esc(safeURL(l.video_url))}" target="_blank" rel="noopener noreferrer">YouTube에서 열기 ↗ (외부 시청은 기록되지 않음)</a>`:''}</div>`:''}<div class="detail-section"><h3>이번 수업 과제</h3>${tasks.map(a=>`<div class="list-row"><div><h4>${esc(a.title)}</h4><p>${esc(kindName(a.kind))} · ${esc(fmt(a.due_at,'time'))}</p></div><button class="btn soft tiny" data-act="assignment" data-id="${esc(a.id)}">열기</button></div>`).join('')||'<p class="small muted">등록된 과제가 없습니다.</p>'}</div>`,true);
 if(l.video_kind&&l.video_kind!=='none')await startVideo(l).catch(e=>{const el=$('#watch-status');if(el)el.textContent=e.message;});
}
function safeURL(s){try{const u=new URL(s);return u.protocol==='https:'?u.href:'#';}catch{return '#';}}
function assignmentsView(){const admin=currentUser.role==='admin',sid=studentId(),list=relevantAssignments(admin?null:sid).sort((a,b)=>(Date.parse(b.due_at)||0)-(Date.parse(a.due_at)||0));return pageTitle('LEARNING MISSIONS',admin?'과제와 피드백':'나의 과제',admin?'서버에 기록된 제출 시각을 기준으로 제출 여부와 기한을 확인합니다.':'사진 과제, 클릭 답안, 복습 안내를 한곳에서 확인하세요.')+`<div class="stack">${list.map(a=>{const l=one('lessons',a.lesson_id),s=submissionFor(a.id,sid),subs=by('submissions','assignment_id',a.id),expected=(D.profiles||[]).filter(p=>p.role==='student'&&l&&canAttendLesson(p.id,l)).length;return `<article class="card"><div class="row between wrap"><div class="grow"><div class="detail-chips"><span class="pill">${esc(kindName(a.kind))}</span>${!admin?statusPill(s,a):`<span class="pill good">${a.kind==='text'?'온라인 제출 없음':`${subs.length} / ${expected}명 제출`}</span>`}</div><h3>${esc(a.title)}</h3><p class="small muted mt">${esc(className(l?.class_id))} · ${esc(l?.title||'')}</p><p class="small muted">제출 기한: ${esc(fmt(a.due_at,'time'))}</p></div><button class="btn ${admin?'secondary':'accent'}" data-act="assignment" data-id="${esc(a.id)}">${admin?'제출 현황':'과제 열기'}</button></div></article>`;}).join('')||empty('등록된 과제가 없습니다.')}</div>`;}
function assignmentModal(aid){const a=one('assignments',aid);if(!a)return;const admin=currentUser.role==='admin',parent=currentUser.role==='parent',sid=studentId(),s=submissionFor(aid,sid);photoFiles=[];const items=by('assignment_items','assignment_id',aid).sort((a,b)=>a.item_no-b.item_no);let body=`<div class="row wrap between"><span class="pill">${esc(kindName(a.kind))}</span><span class="small muted">${esc(fmt(a.due_at,'time'))} 마감</span></div><div class="pre mt">${esc(a.instructions)}</div>`;
 if(admin){const subs=by('submissions','assignment_id',aid);body+=`<div class="row wrap mt"><button class="btn secondary tiny" data-act="edit-deadline" data-id="${esc(aid)}">기한·지각 제출 설정</button></div><div class="detail-section"><h3>제출 현황</h3>${subs.map(x=>`<div class="list-row"><div><h4>${esc(studentName(x.student_id))} ${statusPill(x,a)}</h4><p>${esc(fmt(x.submitted_at,'time'))} ${x.score!==null?`· ${x.score}점`:''}</p></div><button class="btn soft tiny" data-act="view-submission" data-id="${esc(x.id)}">제출물 확인</button></div>`).join('')||empty('아직 제출된 과제가 없습니다.')}</div>`;
 const l=one('lessons',a.lesson_id);const missing=studentsOf(l?.class_id).filter(p=>canAttendLesson(p.id,l)&&!subs.some(s=>s.student_id===p.id));if(a.kind!=='text')body+=`<div class="notice mt">미제출: ${esc(missing.map(p=>p.display_name).join(', ')||'없음')}</div>`;
 }else if(s){body+=`<div class="notice mt">${s.late?'기한 후 제출':'제출 완료'} · ${esc(fmt(s.submitted_at,'time'))}${s.score!==null?` · ${s.score}점`:''}</div>${s.asset_ids?.length?`<div class="stack mt">${s.asset_ids.map((x,i)=>`<button class="material-link" data-act="asset" data-id="${esc(x)}">제출 사진 ${i+1}${icon('download')}</button>`).join('')}</div>`:''}${s.answers?.length?`<div class="detail-section"><h3>제출한 답안</h3><p class="small pre">${s.answers.map((ans,i)=>`${i+1}번: ${ans}`).join('　')}</p></div>`:''}${s.feedback?`<div class="detail-section"><h3>선생님의 피드백</h3><div class="feedback-box pre">${esc(s.feedback)}</div></div>`:''}`;
 }else if(a.kind==='text'){body+='<div class="notice mt">이 과제는 온라인 제출을 받지 않습니다. 안내된 내용을 준비해 오세요.</div>';}
 else if(parent){body+='<div class="notice mt">아직 학생이 제출하지 않았습니다. 학부모 계정은 학생 대신 답안이나 사진을 제출할 수 없습니다.</div>';}
 else if(a.due_at&&Date.parse(a.due_at)<Date.now()&&!a.accept_late){body+='<div class="notice warn mt">제출 기한이 지났습니다. 선생님께 문의해 주세요.</div>';}
 else if(a.kind==='quiz'){body+=`<form class="mt" data-form="submit-quiz" data-id="${esc(a.id)}"><div class="notice mb">총 ${a.question_count}문항입니다. 최종 제출 후에는 답안을 바꿀 수 없습니다.</div><div class="quiz-grid">${items.map(i=>`<div class="quiz-line"><span class="quiz-no">${i.item_no}번</span>${Array.from({length:i.choices},(_,v)=>`<label class="answer-option"><input type="radio" name="q${i.item_no}" value="${v+1}" required aria-label="${i.item_no}번 답 ${v+1}"><span>${v+1}</span></label>`).join('')}</div>`).join('')}</div>${formEnd('답안 최종 제출')}`;}
 else{body+=`<form class="mt" data-form="submit-photo" data-id="${esc(a.id)}"><label class="upload-zone"><input type="file" id="photo-input" accept="image/*" multiple><h3>사진을 선택해 주세요</h3><p>사진 1~8장 · JPG·PNG·WebP<br>제출 전에 방향과 글자가 잘 보이는지 확인해 주세요.</p></label><div class="field mt"><label>바로 촬영해서 추가하기</label><input id="camera-input" type="file" accept="image/*" capture="environment"></div><div class="photo-previews" id="photo-previews"></div><p id="photo-count" class="small muted mt">선택된 사진이 없습니다.</p><button type="button" class="text-btn" data-act="clear-photos">사진 다시 선택</button>${formEnd('사진 최종 제출')}`;}
 modal(a.title,body);}
function assignmentCreate(lid){modal('수업 과제 추가',`<form data-form="create-assignment" data-id="${esc(lid)}">${field('과제 제목','title','','text','required maxlength="200"')}${textArea('과제 안내','instructions','','required')}${select('제출 방식','kind',[['text','안내만 제공 · 온라인 제출 없음'],['photo','사진으로 온라인 제출'],['quiz','답안을 클릭하여 온라인 제출']],'text')}<div class="form-grid">${field('제출 마감 (한국 시간, 선택)','due_at','','datetime-local')}${field('클릭 답안 문항 수','count',5,'number','min="1" max="100"')}</div><label class="check"><input type="checkbox" name="accept_late">기한이 지난 뒤에도 제출 허용 (지각 제출로 표시)</label><div id="quiz-settings" class="hidden"><div class="notice mb">정답은 서버에서만 저장·채점합니다. 단원·유형을 입력해 두면 오답 기반 추가문제 추천에 사용됩니다.</div><div class="row between mb"><span class="small">번호 / 정답 / 단원 / 유형</span><button type="button" class="btn secondary tiny" data-act="make-quiz-items">문항 설정 적용</button></div><div id="quiz-key-rows"></div></div>${formEnd('과제 등록')}`,true);makeQuizRows();}
function makeQuizRows(){const n=Math.min(100,Math.max(1,asNum($('[name="count"]',$('#modal'))?.value)||5));const box=$('#quiz-key-rows');if(!box)return;const previous={};$$('.quiz-key-grid',box).forEach(el=>{previous[el.dataset.i]={answer:$('select',el)?.value,unit:$('[data-field="unit"]',el)?.value,type:$('[data-field="type"]',el)?.value};});box.innerHTML=Array.from({length:n},(_,i)=>`<div class="quiz-key-grid" data-i="${i+1}"><span class="small muted">${i+1}</span><select class="input" data-field="answer" aria-label="${i+1}번 정답">${[1,2,3,4,5].map(x=>`<option value="${x}" ${String(previous[i+1]?.answer)===String(x)?'selected':''}>${x}</option>`).join('')}</select><input class="input" data-field="unit" aria-label="${i+1}번 단원" placeholder="예: 화학 변화" value="${esc(previous[i+1]?.unit||'')}"><input class="input" data-field="type" aria-label="${i+1}번 유형" placeholder="예: 중화 양적 관계" value="${esc(previous[i+1]?.type||'')}"></div>`).join('');}
function deadlineModal(aid){const a=one('assignments',aid);modal('제출 기한 설정',`<form data-form="assignment-deadline" data-id="${esc(aid)}">${field('마감 (한국 시간)','due_at',localInput(a.due_at),'datetime-local')}<label class="check"><input type="checkbox" name="accept_late" ${a.accept_late?'checked':''}>기한 후 제출 허용</label><div class="notice">이미 기록된 제출 시각과 당시 지각 여부는 바꾸지 않습니다.</div>${formEnd()}`);}
function submissionModal(sid){const s=one('submissions',sid);if(!s)return;const a=one('assignments',s.assignment_id);modal(`${studentName(s.student_id)} · 제출물`,`${statusPill(s,a)} <span class="small muted">${esc(fmt(s.submitted_at,'time'))}</span>${s.asset_ids?.length?`<div class="stack mt">${s.asset_ids.map((x,i)=>`<button class="material-link" data-act="asset" data-id="${esc(x)}">제출 사진 ${i+1}${icon('download')}</button>`).join('')}</div>`:''}${s.answers?.length?`<div class="detail-section"><h3>제출 답안</h3><p class="small pre">${s.answers.map((v,i)=>`${i+1}번: ${v}`).join('　')}</p></div>`:''}<div class="notice mt">Drive 추가 보관: ${esc({done:'완료',failed:'실패 · 원본은 보관됨',copying:'복사 중',not_connected:'미연결 · 원본은 보관됨',not_needed:'사진 없음',not_requested:'대기'}[s.drive_status]||s.drive_status)}</div>${s.asset_ids?.length?`<button class="text-btn" data-act="drive-retry" data-id="${esc(s.id)}">Drive 보관 재시도</button>`:''}<form class="mt" data-form="feedback" data-id="${esc(s.id)}">${field('점수 (사진 과제는 선택, 100점 기준)','score',s.score??'','number','min="0" max="100" step="0.1"')}${textArea('학생·학부모에게 전달할 피드백','feedback',s.feedback||'')}${formEnd('피드백 저장')}`);}
function attendanceModal(lid){const l=one('lessons',lid);const roster=studentsOf(l.class_id).filter(p=>canAttendLesson(p.id,l));modal('출결 기록 · '+l.title,`<form data-form="attendance" data-id="${esc(lid)}"><div class="notice mb">실제 출결만 기록합니다. 페이지 접속이나 영상 재생을 출석으로 자동 처리하지 않습니다.</div>${roster.map(p=>{const a=(D.attendance||[]).find(x=>x.student_id===p.id&&x.lesson_id===lid);return `<div class="row between mb"><span>${esc(p.display_name)}</span><select class="input" name="${esc(p.id)}" style="max-width:170px" aria-label="${esc(p.display_name)} 출결"><option value="">미기록</option>${[['present','출석'],['late','지각'],['absent','결석'],['excused','사유 인정']].map(([v,t])=>`<option value="${v}" ${a?.status===v?'selected':''}>${t}</option>`).join('')}</select></div>`;}).join('')||empty('배정된 학생이 없습니다.')}${formEnd('출결 저장')}`);}
function scoreModal(sid='',cid=''){modal('평가 성적 입력',`<form data-form="save-score">${select('학생','student_id',(D.profiles||[]).filter(p=>p.role==='student').map(p=>[p.id,`${p.display_name} · ${p.school}`]),sid)}${select('반','class_id',(D.classes||[]).map(c=>[c.id,c.name]),cid)}${field('평가 이름','title','','text','required maxlength="150" placeholder="예: 2차 실전 모의고사"')}<div class="form-grid">${field('받은 점수','score','','number','required min="0" step="0.1"')}${field('만점','max_score',100,'number','required min="1" step="0.1"')}</div>${field('평가일','assessed_on',day(),'date','required')}${textArea('평가 피드백 (학생·학부모에게 공개)','note','')}${formEnd('성적 기록')}`);}
function recordsView(){const sid=studentId();const st=studentStats(sid);const courses=classesOf(sid);const worksheets=by('worksheets','student_id',sid);return pageTitle('GROWTH, IN PERSPECTIVE',`${studentName(sid)} 학생의 학습 기록`,'반이 달라져도 기록은 계속 이어집니다.')+`<div class="grid3">${metric('기록된 출석',st.attended.length,'회',`수업 시간 합계 ${Math.round(st.minutes/60)}시간`,'classes')}${metric('누적 평가 기록',st.scores.length,'건','선생님이 등록한 평가','records')}${metric('완료한 온라인 과제',by('submissions','student_id',sid).length,'건','실제 제출된 과제만 집계','assignments')}</div><section class="card mt"><div class="section-heading"><h2>평가 기록</h2></div><div class="toolbar"><select class="input" id="record-class" aria-label="성적 반 선택">${courses.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></div><div id="record-chart">${chart(st.scores.filter(x=>x.class_id===courses[0]?.id).slice(-8))}</div><div class="table-wrap"><table><thead><tr><th>평가일</th><th>평가</th><th>점수</th><th>학습 피드백</th></tr></thead><tbody>${[...st.scores].reverse().map(s=>`<tr><td>${esc(s.assessed_on)}</td><td>${esc(s.title)}<small>${esc(className(s.class_id))}</small></td><td>${s.score} / ${s.max_score}</td><td>${esc(s.note||'—')}</td></tr>`).join('')||'<tr><td colspan="4">성적 기록이 없습니다.</td></tr>'}</tbody></table></div></section><div class="grid2 mt"><section class="card"><div class="section-heading"><h2>출결 기록</h2></div><div class="pending-list">${by('attendance','student_id',sid).map(a=>{const l=one('lessons',a.lesson_id);return `<div class="list-row"><div><h4>${esc(l?.title||'수업')}</h4><p>${esc(fmt(l?.starts_at))}</p></div><span class="pill ${a.status==='absent'?'bad':'good'}">${esc({present:'출석',late:'지각',absent:'결석',excused:'사유 인정'}[a.status])}</span></div>`;}).join('')||empty('출결 기록이 없습니다.')}</div></section><section class="card"><div class="section-heading"><h2>영상 시청 기록</h2></div>${by('watch','student_id',sid).map(w=>`<div class="list-row"><div><h4>${esc(one('lessons',w.lesson_id)?.title||'수업')}</h4><p>화면 표시·재생 상태에 근거한 시간</p></div><span class="pill good">${Math.floor(w.active_seconds/60)}분 ${Math.floor(w.active_seconds%60)}초</span></div>`).join('')||empty('아직 시청 기록이 없습니다.')}<div class="notice mt">집중도나 눈의 시선을 측정하지 않습니다. 다른 앱·YouTube에서 시청한 시간은 포함되지 않습니다.</div></section></div><section class="card mt"><div class="section-heading"><h2>나만의 추가문제 · 오답박살내기</h2></div>${worksheets.map(w=>`<div class="list-row"><div><h4>${esc(w.title)}</h4><p>${esc(fmt(w.created_at))} · ${w.question_ids.length}문항</p></div><button class="btn soft tiny" data-act="asset" data-id="${esc(w.asset_id)}">PDF 받기</button></div>`).join('')||empty('새로운 맞춤 학습지를 기다리고 있습니다.','선생님이 승인하여 배부한 학습지만 표시됩니다.')}</section>`;}
function accountView(force=false){return `<div class="card account-card"><div class="row gap8 mb"><div class="avatar">${esc(currentUser.display_name.slice(0,1))}</div><div><h3>${esc(currentUser.display_name)}</h3><p class="small muted">${esc(roleLabel(currentUser.role))} · 고유번호 ${esc(currentUser.id.slice(0,8))}</p></div></div><form data-form="change-credentials">${field('로그인 아이디','username',currentUser.username,'text','required minlength="2" maxlength="40" autocomplete="username"')}${field('현재 비밀번호','current_password','','password','required autocomplete="current-password"')}${field('새 비밀번호','new_password','','password',`${force?'required ':''}minlength="${demo?4:12}" maxlength="128" autocomplete="new-password"`,'운영에서는 영문·숫자를 포함해 12자 이상입니다. 아이디만 바꾸려면 비워 두세요.')}${field('새 비밀번호 다시 입력','confirm_password','','password',`${force?'required ':''}autocomplete="new-password"`)}<p class="form-error"></p><button class="btn accent" type="submit">계정 정보 변경</button></form><hr><div class="notice">기존 비밀번호는 화면에 표시하거나 복구하지 않습니다. 분실 시 선생님이 새 초기 비밀번호를 발급합니다.${demo?' 이 화면은 체험 모드이므로 새로고침하면 초기 상태로 돌아갑니다.':''}</div><button class="btn secondary mt" data-act="logout">로그아웃</button></div>`;}
function settingsView(){return pageTitle('STUDIO SETTINGS','학습 공간 설정','학생·학부모에게 보이지 않는 관리자 전용 설정입니다.')+`<section class="card account-card"><div class="section-heading"><h2>Google Drive 과제 보관</h2><span class="pill">관리자 전용</span></div><div class="notice mb">제출 사진은 Supabase 비공개 저장소에 먼저 저장됩니다. Google Drive는 추가 보관용이며, 연결 오류가 발생해도 원본 제출 기록을 유지합니다.</div><div id="drive-state" class="small muted mb">연결 상태를 확인하고 있습니다.</div><div class="row wrap"><button class="btn accent" data-act="drive-connect">Google Drive 연결</button><button class="btn secondary" data-act="drive-picker">기존 폴더 선택·승인</button><button class="text-btn" data-act="drive-disconnect">연결 해제</button></div><hr><form data-form="drive-folder">${field('과제를 저장할 Drive 폴더 링크','folder','','url','placeholder="https://drive.google.com/drive/folders/..." required','기존 폴더는 먼저 ‘기존 폴더 선택·승인’으로 접근을 허용하세요. 연결 시 자동 생성되는 폴더도 사용할 수 있습니다.')}<p class="form-error"></p><button class="btn secondary" type="submit">폴더 연결 확인·저장</button></form><p class="small-info mt">Google 연결은 선생님 계정으로 한 번만 합니다. 학생·학부모에게 Google 로그인을 요구하지 않습니다. 테스트 상태의 OAuth 연결은 장기 유지되지 않을 수 있습니다.</p></section><section class="card account-card mt"><h2>운영 점검</h2><div class="status-grid"><span>현재 모드</span><b>${demo?'가상 데이터 미리보기':'Supabase 연결 모드'}</b></div><div class="status-grid"><span>데이터 저장</span><b>${demo?'이 브라우저 탭의 임시 메모리':'Supabase · 비공개 접근 정책'}</b></div><div class="status-grid"><span>시간 기준</span><b>한국 표준시 · 서버 제출 시간</b></div><div class="status-grid"><span>문제은행 자동 추천</span><b>검수된 문항 · 태그 기반</b></div><div class="row wrap mt"><button class="btn secondary" data-act="backup-json">관리 데이터 JSON 내보내기</button><button class="btn secondary" data-act="nav" data-id="account">내 계정 보안</button></div><div class="notice warn mt">JSON 내보내기는 계정·성적 등의 조회 데이터입니다. 인증 정보와 원본 파일은 포함하지 않아 전체 복구용 백업이 아닙니다. 개인정보가 포함될 수 있으므로 별도로 안전하게 보관하세요.</div></section>`;}
async function loadDriveStatus(){const r=await api('drive-status');const el=$('#drive-state');if(!el)return;el.innerHTML=r.connected?`<span class="pill good">연결됨</span> <a href="https://drive.google.com/drive/folders/${esc(r.folder_id)}" target="_blank" rel="noopener">현재 보관 폴더 열기 ↗</a>`:'아직 연결되지 않았습니다. 제출 기능은 Drive 없이도 사용할 수 있습니다.';const f=$('[name="folder"]');if(f&&r.folder_id)f.value='https://drive.google.com/drive/folders/'+r.folder_id;}
async function loadScript(src){if(document.querySelector(`script[src="${src}"]`)){await delay(250);return;}await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('외부 기능을 불러오지 못했습니다. 인터넷 연결을 확인하세요.'));document.head.append(s);});}
async function drivePicker(){if(demo)return toast('미리보기에서는 외부 계정을 연결하지 않습니다. 실제 운영 설정 후 사용할 수 있습니다.');if(!C.googlePickerKey||!C.googleProjectNumber)throw new Error('설치 도우미에 Google Picker API 키와 프로젝트 번호를 입력하고 사이트 파일을 다시 생성하세요.');const r=await api('drive-picker-token');await loadScript('https://apis.google.com/js/api.js');await new Promise(resolve=>window.gapi.load('picker',{callback:resolve}));const view=new google.picker.DocsView(google.picker.ViewId.FOLDERS).setIncludeFolders(true).setSelectFolderEnabled(true);const picker=new google.picker.PickerBuilder().addView(view).setOAuthToken(r.access_token).setDeveloperKey(C.googlePickerKey).setAppId(C.googleProjectNumber).setOrigin(location.origin).setCallback(async data=>{if(data.action===google.picker.Action.PICKED){try{await api('drive-folder',{folder:data.docs[0].id});toast('과제 보관 폴더를 변경했습니다.');await loadDriveStatus();}catch(e){toast(e.message);}}}).build();picker.setVisible(true);}
function saveFile(name,blob){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
async function assetURL(aid){if(demo){const x=(D.assets||[]).find(a=>a.id===aid);if(!x?.url)throw new Error('미리보기에는 이 파일의 원본이 없습니다.');return x.url;}return (await api('asset-url',{id:aid})).url;}
async function openAsset(aid){const win=window.open('about:blank','_blank');if(win){win.opener=null;win.document.body.textContent='보안 파일 링크를 준비하고 있습니다.';}try{const url=await assetURL(aid);if(win)win.location=url;else{toast('팝업이 차단되어 현재 화면에서 파일을 엽니다.');location.assign(url);}}catch(e){if(win)win.close();throw e;}}
async function compressImage(file,max=1800){
 if(file.size>40*1024*1024)throw new Error('사진이 너무 큽니다. 40MB 이하 사진을 선택해 주세요.');
 const url=URL.createObjectURL(file);let img;
 try{img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('사진을 읽지 못했습니다. HEIC 사진은 JPG로 변환하거나 카메라로 다시 촬영해 주세요.'));i.src=url;});const ratio=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*ratio));c.height=Math.max(1,Math.round(img.height*ratio));const ctx=c.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.9));if(!blob)throw new Error('사진 변환에 실패했습니다.');return new File([blob],file.name.replace(/\.[^.]*$/,'')+'.jpg',{type:'image/jpeg'});}finally{URL.revokeObjectURL(url);}
}
async function upload(file,kind,extra={}){
 if(demo){const aid=id();D.assets.push({id:aid,name:file.name,kind,url:URL.createObjectURL(file),blob:file,bytes:file.size,mime:file.type,created_at:new Date().toISOString()});return aid;}
 const p=await api('upload-plan',{kind,name:file.name,mime:file.type,bytes:file.size,...extra});const {error}=await sb.storage.from(p.bucket).uploadToSignedUrl(p.path,p.token,file,{contentType:file.type});if(error)throw new Error('파일 업로드에 실패했습니다. 인터넷 연결과 파일 용량을 확인하세요.');await api('upload-finish',{id:p.id});return p.id;
}
async function addPhotos(files){if(photoFiles.length+files.length>8)throw new Error('사진은 최대 8장입니다.');for(const f of files){const converted=await compressImage(f,1800);photoFiles.push(converted);}renderPhotos();}
function renderPhotos(){const p=$('#photo-previews');if(!p)return;p.innerHTML=photoFiles.map((f,i)=>`<img src="${esc(URL.createObjectURL(f))}" alt="제출 예정 사진 ${i+1}">`).join('');$('#photo-count').textContent=`${photoFiles.length}장 선택됨 · 사진 방향과 글자를 확인해 주세요.`;}
function youtubeId(s){try{const u=new URL(s);if(u.hostname==='youtu.be')return u.pathname.slice(1).split('/')[0];if(/(^|\.)youtube\.com$/.test(u.hostname)||u.hostname==='www.youtube-nocookie.com')return u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).at(-1);}catch{}return '';}
async function startVideo(l){
 const student=currentUser.role==='student';let player=null,video=null,timer=null,stopped=false,pending=0,seq=0,session=null,last=performance.now(),lastPos=null,inViewport=true,inflight=false,total=0;
 const setStatus=s=>{const e=$('#watch-status');if(e)e.textContent=s;};const counter=()=>{const e=$('#watch-seconds');if(e)e.textContent=`${Math.floor((total+pending)/60)}분 ${Math.floor((total+pending)%60)}초`;};
 if(student){const r=await api('watch-start',{lesson_id:l.id});session=r.session_id;total=by('watch','student_id',currentUser.id).find(w=>w.lesson_id===l.id)?.active_seconds||0;}
 if(l.video_kind==='youtube'){const vid=youtubeId(l.video_url);if(!/^[\w-]{11}$/.test(vid))throw new Error('YouTube 영상 주소를 확인하세요.');if(!window.YT?.Player){await new Promise((resolve,reject)=>{const old=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{if(old)old();resolve();};loadScript('https://www.youtube.com/iframe_api').catch(reject);setTimeout(()=>{if(window.YT?.Player)resolve();else reject(new Error('YouTube 플레이어를 불러오지 못했습니다.'));},12000);});}
 if(!$('#video-player'))return;player=await new Promise(resolve=>{const p=new YT.Player('video-player',{host:'https://www.youtube-nocookie.com',videoId:vid,playerVars:{playsinline:1,origin:location.origin,rel:0},events:{onReady:()=>resolve(p),onError:()=>setStatus('영상 제공자가 재생을 허용하지 않았습니다. YouTube에서 열기를 사용하세요.')}});});
 }else{const url=l.video_kind==='upload'?await assetURL(l.video_asset_id):safeURL(l.video_url);const box=$('#video-box');if(!box)return;video=document.createElement('video');video.src=url;video.controls=true;video.playsInline=true;video.preload='metadata';box.replaceChildren(video);video.addEventListener('error',()=>setStatus('재생 링크 또는 영상 형식을 확인하세요. 보안 링크 만료 시 수업을 다시 여세요.'));}
 const pos=()=>player?player.getCurrentTime():video?.currentTime||0;const duration=()=>player?player.getDuration():video?.duration||0;const rate=()=>player?player.getPlaybackRate():video?.playbackRate||1;const playing=()=>player?player.getPlayerState()===1:video&&!video.paused&&!video.ended&&video.readyState>=3;
 async function flush(final=false){if(!student||!session||inflight||!pending)return;inflight=true;const seconds=Math.min(20,pending);pending=0;const n=++seq;try{const r=await api('watch-ping',{lesson_id:l.id,session_id:session,seq:n,seconds,position:Math.max(0,pos()),duration:Number.isFinite(duration())?duration():0},final);total=Number(r.active_seconds);}catch(e){setStatus('기록 전송 실패: '+e.message);}finally{inflight=false;counter();}}
 function tick(){const now=performance.now(),elapsed=(now-last)/1000;last=now;const p=pos(),delta=lastPos===null?0:p-lastPos;const active=!document.hidden&&document.hasFocus()&&inViewport&&playing()&&elapsed>0&&elapsed<2.5&&delta>0&&delta<=elapsed*rate()+1.5;lastPos=p;if(student&&active)pending+=elapsed;setStatus(student?(active?'화면 표시·재생 시간이 기록되고 있습니다.':'일시정지·탭 이동·화면 이탈 중에는 기록하지 않습니다.'):'미리보기 재생 · 학생 시청 기록에 포함되지 않습니다.');counter();if(pending>=9)flush();}
 const observer=typeof IntersectionObserver!=='undefined'?new IntersectionObserver(entries=>{inViewport=entries[0].intersectionRatio>=.5;},{threshold:[0,.5,1]}):null;if(observer)observer.observe($('#video-box'));
 const hidden=()=>{if(document.hidden)flush(true);last=performance.now();lastPos=pos();};document.addEventListener('visibilitychange',hidden);window.addEventListener('pagehide',hidden);timer=setInterval(tick,1000);setStatus(student?'재생 버튼을 누르면 기록이 시작됩니다.':'학생이 아닌 계정의 재생 시간은 기록하지 않습니다.');
 cleanupVideo=()=>{if(stopped)return;stopped=true;clearInterval(timer);flush(true);document.removeEventListener('visibilitychange',hidden);window.removeEventListener('pagehide',hidden);observer?.disconnect();if(video){video.pause();video.removeAttribute('src');video.load();}if(player)try{player.destroy();}catch{}};
}

const actions={
 'nav':el=>navigate(el.dataset.id), 'close-modal':closeModal,
 'logout':async()=>{stopVideo();if(sb)await sb.auth.signOut({scope:'local'});currentUser=null;child=null;D={};tab='home';closeModal();loginView();},
 'choose-child':()=>{child=null;tab='home';render();},
 'select-child':el=>{child=el.dataset.id;tab='home';render();},
 'new-user':newUserModal,'family-modal':familyModal,
 'assign-existing':el=>enrollModal(el.dataset.id),
 'enroll-class':el=>enrollModal('',el.dataset.id),
 'unlink-family':async el=>{if(!confirm('이 가족 연결을 해제할까요? 학생의 학습 기록은 삭제되지 않습니다.'))return;await api('family-link',{parent_id:el.dataset.parent,student_id:el.dataset.id,remove:true});await loadData();familyModal();toast('가족 연결을 해제했습니다.');},
 'random-password':()=>{const bytes=crypto.getRandomValues(new Uint8Array(10));const v='At!'+[...bytes].map(x=>'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789'[x%51]).join('')+'9';const input=$('[name="password"]',$('#modal'));if(input)input.value=v;},
 'reset-password':el=>modal('초기 비밀번호 새로 발급',`<form data-form="reset-password" data-id="${esc(el.dataset.id)}"><div class="notice mb">${esc(studentName(el.dataset.id))} 계정에 임시 비밀번호를 새로 발급합니다. 기존 비밀번호는 열람할 수 없습니다.</div>${field('새 초기 비밀번호','password','','text',`required minlength="${demo?4:12}" autocomplete="off"`)}<button class="text-btn" type="button" data-act="random-password">안전한 초기 비밀번호 자동 만들기</button>${formEnd('새 초기 비밀번호 발급')}`),
 'toggle-active':async el=>{const p=one('profiles',el.dataset.id);if(!confirm(`${p.display_name} 계정을 ${p.active?'비활성화':'활성화'}할까요? 기록은 삭제하지 않습니다.`))return;await api('set-active',{id:p.id,active:!p.active});await refresh();},
 'new-class':()=>classModal(),'edit-class':el=>classModal(one('classes',el.dataset.id)),
 'class':el=>{tab='classes';chosenClass=el.dataset.id;render();},
 'new-lesson':el=>lessonModal({},el.dataset.id),'edit-lesson':el=>lessonModal(one('lessons',el.dataset.id)),
 'lesson':el=>lessonView(el.dataset.id),'assignment':el=>assignmentModal(el.dataset.id),
 'new-assignment':el=>assignmentCreate(el.dataset.id),'make-quiz-items':makeQuizRows,
 'edit-deadline':el=>deadlineModal(el.dataset.id),'view-submission':el=>submissionModal(el.dataset.id),
 'attendance-modal':el=>attendanceModal(el.dataset.id),
 'new-score':el=>scoreModal(el?.dataset.student||'',el?.dataset.class||''),
 'asset':el=>openAsset(el.dataset.id),'clear-photos':()=>{photoFiles=[];renderPhotos();},
 'drive-connect':async()=>{if(demo)return toast('미리보기에서는 Google 계정을 연결하지 않습니다.');const r=await api('drive-start');location.assign(r.url);},
 'drive-picker':drivePicker,
 'drive-disconnect':async()=>{if(!confirm('Drive 추가 보관 연결을 해제할까요? 이미 저장된 파일과 제출 원본은 삭제되지 않습니다.'))return;await api('drive-disconnect');await loadDriveStatus();},
 'drive-retry':async el=>{await api('drive-retry',{submission_id:el.dataset.id});await loadData();submissionModal(el.dataset.id);toast('Drive 보관 상태를 갱신했습니다.');},
 'backup-json':async()=>{if(!confirm('개인정보가 포함될 수 있는 관리 데이터 파일을 이 기기에 저장할까요?'))return;const data={...D};delete data.passwords;delete data.assets;saveFile('ATOMOS_관리데이터_'+day()+'.json',new Blob([JSON.stringify({exported_at:new Date().toISOString(),not_full_backup:true,data},null,2)],{type:'application/json'}));}
};
const forms={
 'login':async(f,v)=>{const r=await api('login',{username:v.username,password:v.password});if(demo){currentUser=r.profile;}else{await sb.auth.setSession(r.session);currentUser=r.profile;}previousSeen=r.previous_seen_at;child=null;await loadData();tab=currentUser.must_change?'account':'home';await render();},
 'create-user':async(f,v)=>{const same=(D.profiles||[]).filter(p=>p.role==='student'&&p.display_name===v.display_name.trim());if(v.role==='student'&&same.length&&!v.confirmed_distinct)throw new Error('같은 이름의 기존 학생을 먼저 확인해 주세요. 다른 학생일 때만 확인란을 선택하세요.');await api('create-user',v);closeModal();await refresh();toast('계정을 만들었습니다. 초기 비밀번호를 본인에게 안전하게 전달하세요.');},
 'enroll':async(f,v)=>{await api('enroll',{...v,access:true});closeModal();await refresh();toast('기존 학생 계정으로 반에 배정했습니다.');},
 'family-link':async(f,v)=>{await api('family-link',v);await loadData();familyModal();toast('학부모에게 자녀를 연결했습니다.');},
 'save-class':async(f,v)=>{if(v.ends_on<v.starts_on)throw new Error('종강일은 개강일 이후여야 합니다.');await api('save-class',{...v,id:f.dataset.id||undefined,active:!!v.active});closeModal();await refresh();toast('반 정보를 저장했습니다.');},
 'save-lesson':async(f,v)=>{
 const old=editingLesson||{};const links=(v.material_links||'').split('\n').map(s=>s.trim()).filter(Boolean).map(s=>{const bar=s.indexOf('|');if(bar<1)throw new Error('자료 링크는 “자료 이름 | https://주소” 형태로 한 줄씩 입력하세요.');return {name:s.slice(0,bar).trim(),url:s.slice(bar+1).trim()};});
 const keep=new FormData(f).getAll('keep_material');const materials=[...(old.materials||[]).filter(m=>m.asset_id&&keep.includes(m.asset_id)),...links];
 for(const file of $('[name="material_files"]',f).files){const aid=await upload(file,'material');materials.push({name:file.name,asset_id:aid});}
 let videoAsset=old.video_asset_id||null;const vf=$('[name="video_file"]',f).files[0];if(v.video_kind==='upload'&&vf)videoAsset=await upload(vf,'video');if(v.video_kind==='upload'&&!videoAsset)throw new Error('영상 파일을 선택해 주세요.');
 await api('save-lesson',{...v,id:f.dataset.id||undefined,starts_at:kst(v.starts_at),duration_min:asNum(v.duration_min),materials,video_asset_id:videoAsset});closeModal();await refresh();toast('수업 기록을 저장했습니다.');},
 'create-assignment':async(f,v)=>{const l=one('lessons',f.dataset.id);let items=[];if(v.kind==='quiz'){const rows=$$('.quiz-key-grid',f);if(rows.length!==asNum(v.count))throw new Error('문항 수를 바꾼 뒤 “문항 설정 적용”을 눌러 주세요.');items=rows.map(r=>({answer:asNum($('[data-field="answer"]',r).value),choices:5,subject:one('classes',l.class_id)?.subject||'',unit:$('[data-field="unit"]',r).value,type_tag:$('[data-field="type"]',r).value}));}
 await api('create-assignment',{lesson_id:f.dataset.id,title:v.title,instructions:v.instructions,kind:v.kind,due_at:kst(v.due_at),accept_late:!!v.accept_late,items});closeModal();await refresh();toast('과제를 등록했습니다.');},
 'assignment-deadline':async(f,v)=>{await api('assignment-deadline',{id:f.dataset.id,due_at:kst(v.due_at),accept_late:!!v.accept_late});closeModal();await refresh();toast('제출 기한을 변경했습니다.');},
 'submit-quiz':async(f,v)=>{const a=one('assignments',f.dataset.id);const answers=Array.from({length:a.question_count},(_,i)=>asNum(v['q'+(i+1)]));if(answers.some(x=>!x))throw new Error('모든 문항에 답해 주세요.');if(!confirm('답안을 최종 제출할까요? 제출 후에는 수정할 수 없습니다.'))return;await api('submit',{assignment_id:a.id,answers,asset_ids:[]});await loadData();assignmentModal(a.id);toast('답안과 제출 시각이 기록되었습니다.');},
 'submit-photo':async(f)=>{if(!photoFiles.length)throw new Error('제출할 사진을 선택해 주세요.');if(!confirm(`${photoFiles.length}장의 사진을 최종 제출할까요?`))return;const aids=[];for(const file of photoFiles)aids.push(await upload(file,'homework',{assignment_id:f.dataset.id}));await api('submit',{assignment_id:f.dataset.id,answers:[],asset_ids:aids});await loadData();assignmentModal(f.dataset.id);toast('사진과 제출 시각이 기록되었습니다.');},
 'attendance':async(f)=>{for(const s of $$('select',f)){if(s.value)await api('attendance',{lesson_id:f.dataset.id,student_id:s.name,status:s.value,note:''});}closeModal();await refresh();toast('출결을 기록했습니다.');},
 'save-score':async(f,v)=>{await api('save-score',{...v,score:asNum(v.score),max_score:asNum(v.max_score)});closeModal();await refresh();toast('평가 성적을 기록했습니다.');},
 'feedback':async(f,v)=>{await api('feedback',{id:f.dataset.id,feedback:v.feedback,...(v.score!==''?{score:asNum(v.score)}:{})});closeModal();await refresh();toast('피드백을 저장했습니다.');},
 'reset-password':async(f,v)=>{await api('reset-password',{id:f.dataset.id,password:v.password});closeModal();await refresh();toast('새 초기 비밀번호를 발급했습니다.');},
 'change-credentials':async(f,v)=>{if(v.new_password!==v.confirm_password)throw new Error('새 비밀번호와 확인 비밀번호가 일치하지 않습니다.');const r=await api('change-credentials',v);if(!demo)await sb.auth.setSession(r.session);await loadData();tab='home';await render();toast('계정 정보를 변경했습니다. 학습 기록은 그대로 유지됩니다.');},
 'drive-folder':async(f,v)=>{await api('drive-folder',v);await loadDriveStatus();toast('과제 보관 폴더를 저장했습니다.');}
};
document.addEventListener('click',async e=>{const el=e.target.closest('[data-act]');if(!el)return;const fn=actions[el.dataset.act];if(!fn)return;e.preventDefault();if(el.disabled)return;try{el.disabled=true;await fn(el);}catch(err){toast(err.message||String(err));}finally{el.disabled=false;}});
document.addEventListener('submit',async e=>{const f=e.target.closest('form[data-form]');if(!f||!forms[f.dataset.form])return;e.preventDefault();if(f.dataset.busy==='1')return;const button=$('button[type="submit"]',f);try{f.dataset.busy='1';if(button)button.disabled=true;const er=$('.form-error',f);if(er)er.textContent='';const v=Object.fromEntries(new FormData(f).entries());await forms[f.dataset.form](f,v);}catch(err){userError(f,err);}finally{f.dataset.busy='';if(button)button.disabled=false;}});
document.addEventListener('input',e=>{if(e.target.id==='user-search'){const b=$('#users-body');if(b)b.innerHTML=userRows();}if(e.target.name==='display_name')duplicateUsers();});
document.addEventListener('change',async e=>{try{if(e.target.id==='user-role')$('#users-body').innerHTML=userRows();if(e.target.name==='role')duplicateUsers();if(e.target.name==='kind'&&$('#quiz-settings'))$('#quiz-settings').classList.toggle('hidden',e.target.value!=='quiz');if(e.target.id==='photo-input'||e.target.id==='camera-input'){await addPhotos([...e.target.files]);e.target.value='';}if(e.target.id==='record-class'){const scores=by('scores','student_id',studentId()).filter(x=>x.class_id===e.target.value).sort((a,b)=>a.assessed_on.localeCompare(b.assessed_on));$('#record-chart').innerHTML=chart(scores.slice(-8));}}catch(err){toast(err.message);}});
$('#modal').addEventListener('close',stopVideo);
window.addEventListener('offline',()=>toast('인터넷 연결이 끊겼습니다. 연결 후 다시 제출해 주세요.'));
window.addEventListener('online',()=>toast('인터넷에 다시 연결되었습니다.'));

// 미리보기 모드는 외부 API에 접근하지 않습니다. 실제 운영 권한 검사는 서버에서 수행합니다.
async function demoAction(action,b){await delay(80);const d=demo;const me=currentUser;
 const add=(table,row)=>{row={...row,id:row.id||id(),created_at:row.created_at||new Date().toISOString()};d[table].push(row);return row;};
 const up=(table,keys,row)=>{const old=d[table].find(x=>keys.every(k=>x[k]===row[k]));if(old){Object.assign(old,row);return old;}return add(table,row);};
 if(action==='login'){const p=d.profiles.find(p=>p.username.normalize('NFKC').toLowerCase()===b.username.trim().normalize('NFKC').toLowerCase());if(!p||d.passwords[p.id]!==b.password)throw new Error('아이디 또는 비밀번호를 확인해 주세요.');if(!p.active)throw new Error('비활성 계정입니다.');return {ok:true,profile:p,previous_seen_at:null};}
 if(!me)throw new Error('로그인이 필요합니다.');
 if(action==='change-credentials'){if(d.passwords[me.id]!==b.current_password)throw new Error('현재 비밀번호를 확인하세요.');const p=d.profiles.find(x=>x.id===me.id);if(d.profiles.some(x=>x.id!==me.id&&x.username===b.username))throw new Error('이미 사용 중인 아이디입니다.');p.username=b.username;if(b.new_password)d.passwords[p.id]=b.new_password;p.must_change=false;return {ok:true};}
 if(action==='watch-start'){const w=up('watch',['student_id','lesson_id'],{student_id:me.id,lesson_id:b.lesson_id,session_id:id(),last_ping:Date.now(),seq:0,...(d.watch.find(w=>w.student_id===me.id&&w.lesson_id===b.lesson_id)?{}:{active_seconds:0})});return {ok:true,session_id:w.session_id};}
 if(action==='watch-ping'){const w=d.watch.find(w=>w.student_id===me.id&&w.lesson_id===b.lesson_id);if(w){w.active_seconds+=Math.min(b.seconds,(Date.now()-w.last_ping)/1000,20);w.last_ping=Date.now();}return {ok:true,active_seconds:w?.active_seconds||0};}
 if(action==='submit'){if(me.role!=='student')throw new Error('학생 계정만 제출할 수 있습니다.');const a=d.assignments.find(x=>x.id===b.assignment_id);if(!a||d.submissions.some(s=>s.assignment_id===a.id&&s.student_id===me.id))throw new Error('이미 제출했거나 없는 과제입니다.');if(a.due_at&&Date.parse(a.due_at)<Date.now()&&!a.accept_late)throw new Error('제출 기한이 지났습니다.');let right=0;if(a.kind==='quiz'){const keys=d.demoKeys?.[a.id]||Array.from({length:a.question_count},(_,i)=>(i%5)+1);right=b.answers.filter((v,i)=>v===keys[i]).length;}
 const s=add('submissions',{assignment_id:a.id,student_id:me.id,submitted_at:new Date().toISOString(),late:!!a.due_at&&Date.parse(a.due_at)<Date.now(),answers:b.answers||[],asset_ids:b.asset_ids||[],score:a.kind==='quiz'?Math.round(right/a.question_count*100):null,total:a.kind==='quiz'?a.question_count:null,feedback:'',drive_status:'not_connected'});
 if(a.kind==='quiz')for(const i of d.assignment_items.filter(i=>i.assignment_id===a.id)){const keys=d.demoKeys?.[a.id]||Array.from({length:a.question_count},(_,i)=>(i%5)+1);d.responses.push({submission_id:s.id,student_id:me.id,assignment_id:a.id,item_no:i.item_no,response:b.answers[i.item_no-1],correct:b.answers[i.item_no-1]===keys[i.item_no-1],question_id:i.question_id||null,subject:i.subject,unit:i.unit,type_tag:i.type_tag});}return {ok:true,submission:s};}
 if(me.role!=='admin')throw new Error('관리자 전용 기능입니다.');
 if(action==='create-user'){if(d.profiles.some(p=>p.username===b.username))throw new Error('이미 사용 중인 아이디입니다.');const p=add('profiles',{username:b.username,display_name:b.display_name,role:b.role,school:b.school||'',grade:b.grade||'',active:true,must_change:false});d.passwords[p.id]=b.password;return {ok:true,id:p.id};}
 if(action==='reset-password'){d.passwords[b.id]=b.password;return {ok:true};}
 if(action==='set-active'){d.profiles.find(p=>p.id===b.id).active=b.active;return {ok:true};}
 if(action==='family-link'){if(b.remove)d.family_links=d.family_links.filter(l=>!(l.parent_id===b.parent_id&&l.student_id===b.student_id));else up('family_links',['parent_id','student_id'],b);return {ok:true};}
 if(action==='enroll'){up('enrollments',['class_id','student_id'],{...b,left_on:b.left_on||null});return {ok:true};}
 if(action==='save-class'){const row=b.id?up('classes',['id'],b):add('classes',b);return {ok:true,row};}
 if(action==='save-lesson'){const row=b.id?up('lessons',['id'],b):add('lessons',b);return {ok:true,row};}
 if(action==='create-assignment'){const a=add('assignments',{lesson_id:b.lesson_id,title:b.title,instructions:b.instructions,kind:b.kind,due_at:b.due_at,accept_late:b.accept_late,question_count:b.items.length});d.demoKeys=d.demoKeys||{};d.demoKeys[a.id]=b.items.map(x=>x.answer);b.items.forEach((x,i)=>{const {answer,...rest}=x;d.assignment_items.push({assignment_id:a.id,item_no:i+1,...rest});});return {ok:true,id:a.id};}
 if(action==='assignment-deadline'){Object.assign(d.assignments.find(a=>a.id===b.id),b);return {ok:true};}
 if(action==='attendance'){up('attendance',['lesson_id','student_id'],b);return {ok:true};}
 if(action==='save-score'){if(!d.enrollments.some(e=>e.student_id===b.student_id&&e.class_id===b.class_id))throw new Error('학생이 이 반에 배정되지 않았습니다.');if(b.score>b.max_score)throw new Error('점수는 만점보다 클 수 없습니다.');add('scores',b);return {ok:true};}
 if(action==='feedback'){Object.assign(d.submissions.find(s=>s.id===b.id),b);return {ok:true};}
 if(action==='drive-status')return {ok:true,connected:false};
 if(action.startsWith('drive-'))throw new Error('미리보기에서는 Google 계정을 연결하거나 Drive에 저장하지 않습니다.');
 if(action==='save-question'){if(d.questions.some(q=>q.fingerprint===b.fingerprint&&q.id!==b.id))throw new Error('이미 저장된 동일 문항입니다.');const row=b.id?up('questions',['id'],b):add('questions',b);return {ok:true,row};}
 if(action==='recommend'){const wrong=d.responses.filter(r=>r.student_id===b.student_id&&!r.correct);const tags=new Set(wrong.map(r=>[r.subject,r.unit,r.type_tag].join('|')));const used=new Set(d.worksheets.filter(w=>w.student_id===b.student_id).flatMap(w=>w.question_ids));const rows=d.questions.filter(q=>q.status==='approved'&&tags.has([q.subject,q.unit,q.type_tag].join('|'))&&!used.has(q.id)&&(!b.difficulty||q.difficulty===b.difficulty)).slice(0,b.count||8);return {ok:true,questions:rows,weaknesses:wrong,method:'태그 일치 규칙 기반',insufficient:rows.length<(b.count||8)};}
 if(action==='publish-worksheet'){add('worksheets',b);return {ok:true};}
 throw new Error('미리보기에서 지원하지 않는 동작입니다. 실제 배포 파일의 연결 기능을 확인하세요.');
}

async function init(){
 if(!C.allowZoom){const vp=$('meta[name="viewport"]');if(vp)vp.content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover';}
 const splash=$('#splash');let seen=false;try{seen=sessionStorage.getItem('atomos-splash')==='1';sessionStorage.setItem('atomos-splash','1');}catch{}
 setTimeout(()=>splash?.classList.add('out'),seen?0:3000);
 if(demo){loginView();return;}
 if(!C.supabaseUrl||!C.publicKey){loginView('실제 운영 설정이 아직 없습니다. 설치 도우미에서 설정값을 입력해 사이트 파일을 생성하세요.');$('button[type="submit"]')?.setAttribute('disabled','');return;}
 if(location.hostname.endsWith('.github.io')){loginView('GitHub Pages에서는 실제 비밀번호 로그인을 사용하지 않습니다. GitHub 연동 웹 호스팅 주소로 배포해 주세요.');$('button[type="submit"]')?.setAttribute('disabled','');return;}
 if(location.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(location.hostname)){loginView('실제 운영은 HTTPS 주소에서만 실행합니다. 설치 도우미에서 배포를 완료하세요.');return;}
 try{const {createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm');sb=createClient(C.supabaseUrl,C.publicKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storageKey:'atomos-auth-'+new URL(C.supabaseUrl).hostname.split('.')[0]}});const {data}=await sb.auth.getSession();if(data.session){await loadData();tab=currentUser.must_change?'account':location.hash.startsWith('#settings')&&currentUser.role==='admin'?'settings':'home';await render();}else loginView();
 if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
 }catch(e){loginView(e.message||'연결을 준비하지 못했습니다.');}
}
init();
window.AtomosApp={state,api,refresh,navigate,assetURL,upload,esc,chart};
})();
