/* ATOMOS Question Studio. PDF.js loads only when a source PDF is opened; image PDF export is local. */
(() => {
'use strict';
const SUBJECTS=['통합과학','화학','물질과 에너지','화학 반응의 세계'];
const LEVELS=['하','중하','중','중상','상','최상'];
const STATUS={review:'검수 대기',approved:'승인',archived:'보관'};
const $=(s,e=document)=>e.querySelector(s),$$=(s,e=document)=>[...e.querySelectorAll(s)];
let pdfjsPromise=null;
async function pdfjs(){if(!pdfjsPromise)pdfjsPromise=import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.mjs').then(m=>{m.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.mjs';return m;}).catch(e=>{pdfjsPromise=null;throw new Error('PDF 도구를 불러오지 못했습니다. 인터넷 연결과 CDN 접근을 확인해 주세요.');});return pdfjsPromise;}

const blobCanvas=c=>new Promise((r,j)=>c.toBlob(b=>b?r(b):j(new Error('이미지를 만들지 못했습니다.')),'image/png'));
const imageLoad=url=>new Promise((r,j)=>{const im=new Image();im.onload=()=>r(im);im.onerror=()=>j(new Error('이미지를 읽지 못했습니다. JPG·PNG·WebP 파일을 확인하세요.'));im.src=url;});
async function hashBytes(bytes){if(!crypto.subtle)throw new Error('이 작업은 HTTPS 사이트에서 열어 주세요.');return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');}
function trimBox(b,w,h){const x=Math.max(0,Math.min(b.x,w)),y=Math.max(0,Math.min(b.y,h));return {x,y,w:Math.max(1,Math.min(b.w,w-x)),h:Math.max(1,Math.min(b.h,h-y))};}
function propose(items,viewport,columns=1){
 // This is a layout heuristic, not AI/OCR. Every rectangle needs teacher review.
 const W=viewport.width,H=viewport.height,lines=items.filter(i=>i.str&&i.str.trim()).map(i=>{const t=i.transform;const x=viewport.transform[0]*t[4]+viewport.transform[2]*t[5]+viewport.transform[4];const y=viewport.transform[1]*t[4]+viewport.transform[3]*t[5]+viewport.transform[5];const h=Math.max(10,Math.abs(t[3]*viewport.scale));return {s:i.str.trim(),x,y,h};});
 const boxes=[];for(let col=0;col<columns;col++){
  const left=col*W/columns,right=(col+1)*W/columns;
  const anchors=lines.filter(i=>/^(?:문제\s*)?\d{1,3}\s*[.．)](?:\s|$|[^\d])/.test(i.s)&&i.x>=left&&i.x<left+W/columns*.27&&i.y>H*.025&&i.y<H*.94).sort((a,b)=>a.y-b.y);
  const unique=anchors.filter((a,i)=>!i||a.y-anchors[i-1].y>20*viewport.scale);
  unique.forEach((a,i)=>{const next=unique[i+1];const y=Math.max(0,a.y-a.h*1.5),bottom=next?next.y-next.h*1.9:H*.955;if(bottom-y>30)boxes.push(trimBox({x:Math.max(left+8*viewport.scale,a.x-8*viewport.scale),y,w:right-Math.max(left+8*viewport.scale,a.x-8*viewport.scale)-12*viewport.scale,h:bottom-y},W,H));});
 }
 return {boxes:boxes.slice(0,40),lines};
}
async function mount(root,c){
 if(!root||c.state.me.role!=='admin')return;
 const {esc,field,textArea,select,toast,modal,closeModal}=c;
 let questions=[...c.questions],mode='library',selected=new Set(),filter='',statusFilter='',subjectFilter='',working=false;
 let sourceFile=null,sourceHash='',sourceAsset=null,pdf=null,page=1,pageCount=1,canvas=null,overlay=null,items=[],viewport=null,boxes=[],chosen=-1,drag=null,previewURL=null,lastMetadata={subject:'통합과학',unit:'',type_tag:'',difficulty:'중',license_note:''};
 let recommendations=null,recoStudent='',recoTitle='오답박살내기 · 다시 도전하는 과학';
 const btn=(name,text,extra='',cls='secondary')=>`<button type="button" class="btn ${cls}" data-bank-act="${name}" ${extra}>${text}</button>`;
 const note='<div class="notice mt">자동 분할은 PDF의 글자 위치와 문항 번호를 이용한 <b>경계 제안</b>입니다. 수식·그림은 원본 이미지로 보존합니다. 문항 누락·이어진 문항·2단 편집은 선생님이 확인해야 합니다. 스캔 파일을 실제 OCR 또는 AI로 읽는 기능은 이번 버전에 포함하지 않았습니다.</div>';
 function paint(){
  if(!root.isConnected)return;
  root.innerHTML=`<div class="tabs bank-tabs"><button class="${mode==='library'?'active':''}" data-bank-act="tab" data-value="library">문항 보관함 <span>${questions.length}</span></button><button class="${mode==='import'?'active':''}" data-bank-act="tab" data-value="import">PDF·사진에서 문항 추가</button><button class="${mode==='recommend'?'active':''}" data-bank-act="tab" data-value="recommend">오답 유형 → 추가 학습지</button></div><div id="bank-content"></div>`;
  const el=$('#bank-content',root);if(mode==='library')library(el);else if(mode==='recommend')recommend(el);else studio(el);
 }
 function library(el){const rows=questions.filter(q=>(!statusFilter||q.status===statusFilter)&&(!subjectFilter||q.subject===subjectFilter)&&[q.source_name,q.subject,q.unit,q.type_tag,q.extracted_text].join(' ').toLowerCase().includes(filter.toLowerCase()));
 el.innerHTML=`<div class="metrics compact-metrics"><div class="metric"><span>전체 문항</span><strong>${questions.length}</strong><small>보관한 원본 문항</small></div><div class="metric"><span>배부 가능한 문항</span><strong>${questions.filter(q=>q.status==='approved').length}</strong><small>선생님 검수 승인</small></div><div class="metric"><span>검수 대기</span><strong>${questions.filter(q=>q.status==='review').length}</strong><small>정답·출처·경계 확인 필요</small></div></div><div class="card mt"><div class="toolbar"><input id="bank-search" placeholder="과목·단원·유형·출처 검색" value="${esc(filter)}" aria-label="문항 검색"><select id="bank-subject" aria-label="과목 필터"><option value="">모든 과목</option>${SUBJECTS.map(s=>`<option ${s===subjectFilter?'selected':''}>${esc(s)}</option>`).join('')}</select><select id="bank-status" aria-label="검수 상태"><option value="">모든 상태</option>${Object.entries(STATUS).map(([v,t])=>`<option value="${v}" ${v===statusFilter?'selected':''}>${t}</option>`).join('')}</select>${btn('export-selected',`선택 ${selected.size}문항 PDF`,'','accent')}</div><div class="table-wrap"><table><thead><tr><th>선택</th><th>문항·출처</th><th>분류</th><th>난이도</th><th>상태</th><th>관리</th></tr></thead><tbody>${rows.map(q=>`<tr><td><input type="checkbox" class="bank-check" data-id="${esc(q.id)}" ${selected.has(q.id)?'checked':''} aria-label="문항 선택"></td><td><b>${esc(q.type_tag||'문항')}</b><small>${esc(q.source_name)} · ${q.source_page}쪽</small><small>${esc((q.extracted_text||'텍스트 없음 · 원본 이미지 저장').slice(0,90))}</small></td><td>${esc(q.subject)}<small>${esc(q.unit)}</small></td><td>${esc(q.difficulty)}</td><td><span class="pill ${q.status==='approved'?'good':''}">${STATUS[q.status]}</span></td><td>${btn('edit','보기·수정',`data-id="${esc(q.id)}"`,'secondary tiny')}</td></tr>`).join('')||'<tr><td colspan="6"><div class="empty"><strong>아직 문항이 없습니다.</strong>‘PDF·사진에서 문항 추가’를 눌러 시작하세요.</div></td></tr>'}</tbody></table></div><p class="small muted mt">선택 PDF는 최대 30문항, 문항당 1페이지로 만듭니다. 학생 배부는 ‘오답 유형 → 추가 학습지’에서 승인된 문항만 가능합니다. 보관 상태로 변경해도 이미 배부한 PDF는 자동 회수되지 않습니다.</p></div>`;
 }
 function studio(el){
  el.innerHTML=`<div class="notice mb">① 파일 선택 → ② 문항 경계 확인·직접 드래그 → ③ 과목·단원·유형·정답 입력 → ④ 저장합니다. 파일은 문항 저장 시 처음 서버에 올라갑니다. ${c.state.demo?'현재는 가상 체험이므로 서버에 업로드하지 않습니다.':''}</div><div class="bank-layout"><section class="card"><div class="toolbar"><label class="btn accent">PDF·이미지 선택<input type="file" id="bank-file" accept="application/pdf,image/jpeg,image/png,image/webp" hidden></label><span id="bank-file-name" class="small muted">${esc(sourceFile?.name||'40MB 이하 PDF 또는 이미지')}</span></div><div class="toolbar mt">${btn('page-prev','이전 쪽')}<span id="bank-page-count">${page} / ${pageCount}</span>${btn('page-next','다음 쪽')}<select id="bank-columns" aria-label="편집 단 수"><option value="1">1단 편집</option><option value="2">2단 편집</option></select>${btn('propose','문항 경계 제안')}${btn('clear-boxes','경계 지우기')}</div><div id="bank-canvas-wrap" class="crop-stage"><div class="empty"><strong>파일을 선택해 주세요.</strong>이미지 위에서 마우스로 드래그하면 문항을 자를 수 있습니다.</div></div><p id="bank-crop-hint" class="small muted mt">드래그하여 새 영역을 만들고, 번호 상자를 눌러 저장할 문항을 고르세요.</p>${note}</section><aside class="card bank-editor"><div class="eyebrow">REVIEW BEFORE SAVE</div><h3>문항 확인</h3><div id="bank-preview" class="question-preview"><span class="muted">선택한 문항 미리보기</span></div><form id="bank-meta">${metadata(lastMetadata)}<div class="field"><label for="f-extracted_text">검출한 텍스트 (보조 검색용)</label><textarea name="extracted_text" id="f-extracted_text" rows="4" placeholder="원본 이미지가 기준입니다. 검색용 글자는 수정할 수 있습니다."></textarea></div><p class="form-error" role="alert"></p><button type="submit" class="btn accent full">선택 문항 저장하기</button></form></aside></div>`;
  if(canvas)attachCanvas();
 }
 function metadata(q){return `${select('과목','subject',SUBJECTS,q.subject||'통합과학')}${field('단원','unit',q.unit||'','text','required maxlength="100" placeholder="예: 화학 변화"')}${field('유형','type_tag',q.type_tag||'','text','required maxlength="100" placeholder="예: 중화 반응의 양적 관계"')}<div class="form-grid">${select('난이도','difficulty',LEVELS,q.difficulty||'중')}${select('저장 상태','status',Object.entries(STATUS),q.status||'review')}</div>${field('정답','answer',q.answer||'','text','maxlength="3000" placeholder="예: ③ 또는 서술형 핵심 답"')}${textArea('해설 (관리자에게만 표시)','explanation',q.explanation||'','maxlength="15000"')}${field('출처·사용 권한 확인','license_note',q.license_note||'','text','maxlength="1000" placeholder="예: 직접 제작 · ATOMOS Sci"','출판사 문항은 적법한 이용 권한을 확인하세요. 승인 시 필수입니다.')}`;}
 function recommend(el){const students=c.state.data.profiles.filter(p=>p.role==='student');el.innerHTML=`<div class="grid-2"><div class="card"><div class="eyebrow">A SECOND CHANCE TO UNDERSTAND</div><h2>틀린 이유에서,<br>다음 문제를 찾습니다.</h2><p class="muted mt">학생의 클릭 답안 오답에서 과목·단원·유형을 찾습니다. 같은 태그의 승인 문항 중 이미 배부한 문항을 제외해 후보를 제안합니다.</p><form id="bank-recommend" class="mt">${select('학생','student_id',students.map(s=>[s.id,s.display_name+' · '+s.username]),recoStudent, 'required')}${field('희망 문항 수','count',8,'number','min="1" max="30" required')}${select('난이도','difficulty',[['','모든 난이도'],...LEVELS], '')}<button class="btn accent full" type="submit">오답 유형으로 문항 찾기</button><p class="form-error"></p></form><div class="notice mt">오답 데이터와 문항은행의 태그가 정확히 같아야 연결됩니다. 후보가 모자라면 부족한 수를 그대로 표시합니다. 문제를 새로 지어내거나 과학적 정답을 AI가 확정하지 않습니다.</div></div><div class="card"><h3>선생님 확인 후 배부</h3><div id="bank-reco-result">${recoHTML()}</div></div></div>`;}
 function recoHTML(){if(!recommendations)return '<div class="empty"><strong>학생을 선택하고 문항을 찾아 주세요.</strong>검수 승인된 문항과 채점 기록이 쌓이면 이곳이 연결됩니다.</div>';const list=recommendations.rows||[];return `<p class="small muted mt">요청 ${recommendations.requested}문항 중 ${list.length}문항을 찾았습니다. 문항을 열어 적합성을 확인한 뒤 배부하세요.</p>${list.map(q=>`<label class="reco-item"><input class="bank-check" type="checkbox" data-id="${esc(q.id)}" ${selected.has(q.id)?'checked':''}><span><b>${esc(q.type_tag)}</b><small>${esc(q.subject)} / ${esc(q.unit)} · ${esc(q.difficulty)}</small></span>${btn('edit','문항 확인',`data-id="${esc(q.id)}"`,'secondary tiny')}</label>`).join('')||'<div class="notice warn mt">연결 가능한 승인 문항이 없습니다. 클릭 과제의 문항별 태그와 문제은행 태그를 확인하세요.</div>'}<form id="bank-publish" class="mt">${field('학습지 제목','title',recoTitle,'text','required maxlength="200"')}<label class="check"><input name="approved" type="checkbox" required>문항과 배부 권한을 직접 확인했습니다.</label><p class="form-error"></p><div class="row gap8 wrap">${btn('export-selected','PDF 먼저 확인하기')}<button class="btn accent" type="submit" ${!list.length?'disabled':''}>선택 문항 PDF 만들고 학생에게 배부</button></div></form>`;}
 async function openSource(file){
  if(file.size>40*1024*1024)throw new Error('원본 파일은 40MB 이하로 나누어 주세요.');
  sourceFile=file;sourceAsset=null;page=1;boxes=[];chosen=-1;sourceHash=await hashBytes(await file.arrayBuffer());
  if(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')){const m=await pdfjs();try{pdf=await m.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false,useSystemFonts:true,stopAtErrors:false}).promise;}catch(e){throw new Error('PDF를 읽지 못했습니다. 암호가 걸린 파일은 암호를 해제하고 다시 시도하세요.');}pageCount=pdf.numPages;if(pageCount>300)throw new Error('한 번에 300쪽 이하로 나누어 주세요.');await renderPage();}
  else{if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('JPG·PNG·WebP 또는 PDF를 선택하세요.');pdf=null;pageCount=1;const url=URL.createObjectURL(file);try{const im=await imageLoad(url);const scale=Math.min(1,2400/im.width,3600/im.height);canvas=document.createElement('canvas');canvas.width=Math.round(im.width*scale);canvas.height=Math.round(im.height*scale);canvas.getContext('2d').drawImage(im,0,0,canvas.width,canvas.height);items=[];viewport=null;}finally{URL.revokeObjectURL(url);}paint();}
 }
 async function renderPage(){const p=await pdf.getPage(page),base=p.getViewport({scale:1}),scale=Math.min(2,2400/base.width,3600/base.height);viewport=p.getViewport({scale});canvas=document.createElement('canvas');canvas.width=Math.floor(viewport.width);canvas.height=Math.floor(viewport.height);const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);await p.render({canvasContext:context,viewport}).promise;const text=await p.getTextContent();items=text.items;boxes=[];chosen=-1;paint();}
 function attachCanvas(){const wrap=$('#bank-canvas-wrap',root);if(!wrap)return;wrap.innerHTML='';const inner=document.createElement('div');inner.className='crop-inner';inner.style.position='relative';canvas.style.cssText='display:block;width:100%;height:auto;';inner.append(canvas);overlay=document.createElement('div');overlay.className='crop-overlay';overlay.style.cssText='position:absolute;inset:0;touch-action:none;cursor:crosshair;';inner.append(overlay);wrap.append(inner);overlay.addEventListener('pointerdown',e=>{if(e.target.closest('[data-box]'))return;e.preventDefault();const p=point(e);drag={start:p,box:{x:p.x,y:p.y,w:0,h:0}};overlay.setPointerCapture(e.pointerId);drawBoxes();});overlay.addEventListener('pointermove',e=>{if(!drag)return;const p=point(e),s=drag.start;drag.box=trimBox({x:Math.min(p.x,s.x),y:Math.min(p.y,s.y),w:Math.abs(p.x-s.x),h:Math.abs(p.y-s.y)},canvas.width,canvas.height);drawBoxes();});overlay.addEventListener('pointerup',e=>{if(!drag)return;const b=drag.box;drag=null;if(b.w>25&&b.h>25){boxes.push(b);chosen=boxes.length-1;updatePreview().catch(err=>toast(err.message));}drawBoxes();});overlay.addEventListener('pointercancel',()=>{drag=null;drawBoxes();});overlay.addEventListener('click',e=>{const target=e.target.closest('[data-box]');if(target){chosen=Number(target.dataset.box);drawBoxes();updatePreview().catch(err=>toast(err.message));}});drawBoxes();if(chosen>=0)updatePreview().catch(()=>{});}
 function point(e){const r=overlay.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(e.clientX-r.left)/r.width*canvas.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-r.top)/r.height*canvas.height))};}
 function drawBoxes(){if(!overlay)return;const boxHTML=(b,i)=>`<div class="crop-box ${i===chosen?'selected':''}" data-box="${i}" style="left:${b.x/canvas.width*100}%;top:${b.y/canvas.height*100}%;width:${b.w/canvas.width*100}%;height:${b.h/canvas.height*100}%"><button type="button" data-box="${i}" aria-label="${i+1}번 영역 선택">${i+1}</button></div>`;overlay.innerHTML=boxes.map(boxHTML).join('')+(drag?`<div class="crop-box selected" style="pointer-events:none;left:${drag.box.x/canvas.width*100}%;top:${drag.box.y/canvas.height*100}%;width:${drag.box.w/canvas.width*100}%;height:${drag.box.h/canvas.height*100}%"></div>`:'');}
 async function cropBlob(){const b=boxes[chosen];if(!b)throw new Error('저장할 문항 영역을 먼저 그리거나 선택하세요.');const cr=document.createElement('canvas');cr.width=Math.max(1,Math.round(b.w));cr.height=Math.max(1,Math.round(b.h));const ctx=cr.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,cr.width,cr.height);ctx.drawImage(canvas,b.x,b.y,b.w,b.h,0,0,cr.width,cr.height);return blobCanvas(cr);}
 async function updatePreview(){const blob=await cropBlob();if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(blob);const target=$('#bank-preview',root);if(target)target.innerHTML=`<img src="${previewURL}" alt="선택 문항 원본 미리보기">`;const b=boxes[chosen];const lines=viewport?propose(items,viewport,1).lines:[];const text=lines.filter(i=>i.x>=b.x&&i.x<=b.x+b.w&&i.y>=b.y&&i.y<=b.y+b.h).sort((a,d)=>Math.abs(a.y-d.y)>8?a.y-d.y:a.x-d.x).map(i=>i.s).join(' ');const f=$('[name="extracted_text"]',root);if(f)f.value=text;$('#bank-crop-hint',root).textContent=`현재 ${boxes.length}개 영역 중 ${chosen+1}번 선택 · 경계 수정은 ‘경계 지우기’ 후 다시 드래그하세요.`;}
 async function saveCrop(form){
  const values=Object.fromEntries(new FormData(form));if(values.status==='approved'&&(!values.answer.trim()||!values.license_note.trim()))throw new Error('승인하려면 정답과 출처·사용 권한을 입력하세요.');const blob=await cropBlob(),b=boxes[chosen];
  const fingerprint=await hashBytes(new TextEncoder().encode(sourceHash+'|'+page+'|'+JSON.stringify(Object.fromEntries(Object.entries(b).map(([k,v])=>[k,Math.round(v)])))));if(questions.some(q=>q.fingerprint===fingerprint))throw new Error('이 파일의 같은 영역은 이미 저장되어 있습니다. 보관함에서 수정하세요.');
  if(!sourceAsset)sourceAsset=await c.upload(sourceFile,'source');const image=await c.upload(new File([blob],`question-p${page}-${chosen+1}.png`,{type:'image/png'}),'question');
  const body={...values,image_asset_id:image,source_asset_id:sourceAsset,source_name:sourceFile.name,source_page:page,bbox:{...b,canvas_width:canvas.width,canvas_height:canvas.height,normalized:{x:b.x/canvas.width,y:b.y/canvas.height,w:b.w/canvas.width,h:b.h/canvas.height}},fingerprint,concept_ids:[]};
  const r=await c.api('save-question',body);questions.push(r.row||{id:r.id,...body});lastMetadata={...values,answer:'',explanation:'',status:'review'};toast('문항을 저장했습니다. 다른 영역을 선택해 이어서 저장하세요.');
 }
 async function editQuestion(id){const q=questions.find(q=>q.id===id)||(recommendations?.rows||[]).find(q=>q.id===id);if(!q)throw new Error('문항을 찾을 수 없습니다.');const url=await c.assetURL(q.image_asset_id);modal('문항 원본 확인·분류 수정',`<div class="bank-layout"><div><img class="question-full" src="${esc(url)}" alt="문항 원본"><p class="small muted mt">${esc(q.source_name)} · ${q.source_page}쪽<br>이미지의 경계를 바꾸려면 원본 파일에서 다시 잘라 저장하세요.</p></div><form id="bank-edit-question" data-question="${esc(id)}">${metadata(q)}${textArea('검색용 텍스트','extracted_text',q.extracted_text||'','maxlength="30000"')}<p class="form-error"></p><button class="btn accent" type="submit">변경 저장</button></form></div>`,true);
  $('#bank-edit-question').addEventListener('submit',async e=>{e.preventDefault();e.stopPropagation();const form=e.currentTarget,button=$('[type=submit]',form);button.disabled=true;try{const v=Object.fromEntries(new FormData(form));if(v.status==='approved'&&(!v.answer.trim()||!v.license_note.trim()))throw new Error('정답과 출처·사용 권한을 입력하세요.');const r=await c.api('save-question',{...q,...v});const updated=r.row||{...q,...v};const n=questions.findIndex(x=>x.id===id);if(n<0)questions.push(updated);else questions[n]=updated;if(recommendations)recommendations.rows=recommendations.rows.map(x=>x.id===id?updated:x);closeModal();paint();toast('문항 정보를 변경했습니다.');}catch(err){$('.form-error',form).textContent=err.message;}finally{button.disabled=false;}});
 }
 function picked(){const all=new Map([...questions,...(recommendations?.rows||[])].map(q=>[q.id,q]));return [...selected].map(id=>all.get(id)).filter(Boolean);}
 function makeImagePDF(pages){
  const e=new TextEncoder(),chunks=[],offsets=[0];let size=0;
  const append=b=>{const a=typeof b==='string'?e.encode(b):b;chunks.push(a);size+=a.length;};
  const obj=(n,body,stream)=>{offsets[n]=size;append(`${n} 0 obj\n`);append(body);if(stream){append('\nstream\n');append(stream);append('\nendstream');}append('\nendobj\n');};
  append('%PDF-1.4\n%ATOMOS-SCI\n');obj(1,'<< /Type /Catalog /Pages 2 0 R >>');obj(2,`<< /Type /Pages /Count ${pages.length} /Kids [${pages.map((_,i)=>`${3+i*3} 0 R`).join(' ')}] >>`);
  pages.forEach((jpeg,i)=>{const n=3+i*3,commands=e.encode('q\n595.276 0 0 841.890 0 0 cm\n/Im0 Do\nQ\n');obj(n,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.276 841.890] /Resources << /XObject << /Im0 ${n+2} 0 R >> >> /Contents ${n+1} 0 R >>`);obj(n+1,`<< /Length ${commands.length} >>`,commands);obj(n+2,`<< /Type /XObject /Subtype /Image /Width 1654 /Height 2339 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>`,jpeg);});
  const xref=size,total=3+pages.length*3;append(`xref\n0 ${total}\n0000000000 65535 f \n`);for(let i=1;i<total;i++)append(`${String(offsets[i]).padStart(10,'0')} 00000 n \n`);append(`trailer\n<< /Size ${total} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`);return new Blob(chunks,{type:'application/pdf'});
 }
 async function createPDF(list,title){
  if(!list.length)throw new Error('문항을 먼저 선택하세요.');if(list.length>30)throw new Error('한 번에 최대 30문항까지 만들 수 있습니다.');
  // A small image-only PDF writer. No API, font file or external library is required.
  const pages=[];for(let i=0;i<list.length;i++){
   const q=list[i],url=await c.assetURL(q.image_asset_id),res=await fetch(url);if(!res.ok)throw new Error('문항 이미지를 내려받지 못했습니다.');const b=await res.blob(),u=URL.createObjectURL(b);
   try{const im=await imageLoad(u),sheet=document.createElement('canvas');sheet.width=1654;sheet.height=2339;const g=sheet.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,sheet.width,sheet.height);
    g.fillStyle='#173c33';g.font='600 33px sans-serif';g.fillText('ATOMOS Sci 박지훈',110,123);g.font='600 45px sans-serif';g.fillText(title.slice(0,48),110,203,1434);g.fillStyle='#799083';g.font='24px sans-serif';g.fillText('다시 이해하고, 스스로 해결하는 연습',110,253);g.strokeStyle='#cbd8d0';g.lineWidth=2;g.beginPath();g.moveTo(110,296);g.lineTo(1544,296);g.stroke();
    g.fillStyle='#176453';g.font='600 39px sans-serif';g.fillText(String(i+1).padStart(2,'0'),110,365);const scale=Math.min(1434/im.width,1760/im.height);g.drawImage(im,110,411,im.width*scale,im.height*scale);g.fillStyle='#6c8376';g.font='21px sans-serif';g.fillText(`ATOMOS SCI  ·  ${i+1} / ${list.length}`,110,2269);
    const jpeg=await new Promise((resolve,reject)=>sheet.toBlob(x=>x?resolve(x):reject(new Error('PDF 페이지 이미지를 만들지 못했습니다.')),'image/jpeg',.95));pages.push(new Uint8Array(await jpeg.arrayBuffer()));
   }finally{URL.revokeObjectURL(u);}
  }
  return makeImagePDF(pages);
 }
 const actions={
 'tab':async el=>{mode=el.dataset.value;paint();},
 'page-prev':async()=>{if(!pdf||page<=1)return;if(boxes.length&&!confirm('현재 쪽의 영역 선택은 사라집니다. 저장한 문항은 남습니다. 이전 쪽으로 이동할까요?'))return;page--;await renderPage();},
 'page-next':async()=>{if(!pdf||page>=pageCount)return;if(boxes.length&&!confirm('현재 쪽의 영역 선택은 사라집니다. 저장한 문항은 남습니다. 다음 쪽으로 이동할까요?'))return;page++;await renderPage();},
 'propose':async()=>{if(!pdf||!items.length)throw new Error('글자 정보가 없는 PDF/이미지입니다. 문항 영역을 직접 드래그하세요.');const r=propose(items,viewport,Number($('#bank-columns',root).value));boxes=r.boxes;chosen=boxes.length?0:-1;drawBoxes();if(chosen>=0)await updatePreview();toast(boxes.length?`${boxes.length}개 문항 경계를 제안했습니다. 저장 전 반드시 확인하세요.`:'문항 번호를 찾지 못했습니다. 편집 단 수를 바꾸거나 직접 드래그하세요.');},
 'clear-boxes':async()=>{boxes=[];chosen=-1;drawBoxes();$('#bank-preview',root).innerHTML='<span class="muted">다시 드래그해 주세요.</span>';},
 'edit':async el=>editQuestion(el.dataset.id),
 'export-selected':async()=>{const blob=await createPDF(picked(),mode==='recommend'?$('#f-title',root)?.value||recoTitle:'ATOMOS Sci · 선택 문항');c.saveFile('ATOMOS_추가학습지.pdf',blob);toast('PDF를 만들었습니다. 실제 페이지를 열어 문항 가독성을 확인하세요.');}
 };
 root.addEventListener('click',async e=>{const el=e.target.closest('[data-bank-act]');if(!el||working)return;e.preventDefault();const fn=actions[el.dataset.bankAct];if(!fn)return;working=true;el.disabled=true;try{await fn(el);}catch(err){toast(err.message);}finally{working=false;el.disabled=false;}});
 root.addEventListener('change',async e=>{const t=e.target;if(t.classList.contains('bank-check')){t.checked?selected.add(t.dataset.id):selected.delete(t.dataset.id);if(mode==='library'){const b=$('[data-bank-act="export-selected"]',root);if(b)b.textContent=`선택 ${selected.size}문항 PDF`;}return;}if(t.id==='bank-status'){statusFilter=t.value;paint();}else if(t.id==='bank-subject'){subjectFilter=t.value;paint();}else if(t.id==='bank-file'&&t.files[0]){if(working)return;working=true;try{toast('원본을 읽고 있습니다.');await openSource(t.files[0]);}catch(err){toast(err.message);}finally{working=false;}}});
 let searchTimer;root.addEventListener('input',e=>{if(e.target.id==='bank-search'){filter=e.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{const pos=e.target.selectionStart;paint();const input=$('#bank-search',root);input?.focus();input?.setSelectionRange(pos,pos);},250);}});
 root.addEventListener('submit',async e=>{const form=e.target;if(!['bank-meta','bank-recommend','bank-publish'].includes(form.id))return;e.preventDefault();e.stopPropagation();if(working)return;working=true;const button=$('[type=submit]',form);button.disabled=true;const original=button.textContent;button.textContent='처리 중…';$('.form-error',form).textContent='';try{
  if(form.id==='bank-meta')await saveCrop(form);
  if(form.id==='bank-recommend'){const v=Object.fromEntries(new FormData(form));recoStudent=v.student_id;const r=await c.api('recommend',{...v,count:Number(v.count)});recommendations={rows:r.questions||r.rows||[],requested:Number(v.count)};selected=new Set(recommendations.rows.map(q=>q.id));paint();}
  if(form.id==='bank-publish'){const list=picked();if(!list.length||list.some(q=>q.status!=='approved'))throw new Error('승인 상태인 문항만 선택하세요.');const values=Object.fromEntries(new FormData(form));recoTitle=values.title;if(!values.approved)throw new Error('문항과 사용 권한 확인이 필요합니다.');const blob=await createPDF(list,recoTitle);c.saveFile('ATOMOS_오답박살내기.pdf',blob);const a=await c.upload(new File([blob],'ATOMOS_오답박살내기.pdf',{type:'application/pdf'}),'worksheet',{student_id:recoStudent});await c.api('publish-worksheet',{student_id:recoStudent,title:recoTitle,asset_id:a,question_ids:list.map(q=>q.id)});toast('학생과 연결 학부모의 학습 기록에 학습지를 배부했습니다.');}
 }catch(err){const error=$('.form-error',form);if(error)error.textContent=err.message;toast(err.message);}finally{working=false;button.disabled=false;button.textContent=original;}});
 paint();
}
window.AtomosBank={mount,propose};
})();
